import {esc as e,uid,now,today,dateLabel,timeLabel,validDate,icon,button as b,iconButton as ib,tag,empty,sourceLabel} from './src/utils.js';
import {load,persist,putBlob,getBlob,optimizeUpload,allMedia} from './src/storage.js';
import {home,growth,health,discover,petDetail,photoImage,petNames,reminderItems,visiblePosts} from './src/views.js';
import {localContents,topics} from './src/data.js';
let {state:s,error:readError}=load();
const ui={growthMode:'album',growthSearch:'',growthDate:'',eventType:'all',healthType:'all',discoverTab:'bottle',species:'全部',topic:'',city:'',onlySaved:false,localCity:s.family.city,localDistrict:'',localSpecies:'全部',localType:'',bottleIndex:0};
const routes={home:['我的家','home'],growth:['成长','growth'],health:['健康','health'],discover:['发现','discover']};
const app=document.querySelector('#app'),modal=document.querySelector('#modal'),toastEl=document.querySelector('#toast');
let toastTimer,modalSubmit,focusBefore,mediaUrls=new Map(),previewUrl;
const route=()=>location.hash.slice(1) in routes?location.hash.slice(1):'home';
const currentPet=()=>s.pets.find(p=>p.id===s.selected)||s.pets[0];
function toast(text){toastEl.textContent=text;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),4200);}
function update(fn,{renderNow=true}={}){const next=structuredClone(s);fn(next);const error=persist(next);if(error){toast(error);return false;}s=next;if(renderNow)render();return true;}
function activity(state,text,source='ownerReported',actor='我'){state.activity.unshift({id:uid(),text,source,actor,createdAt:now()});state.activity=state.activity.slice(0,100);}
function navMarkup(v,cls){return `<nav class="${cls}" aria-label="主导航">${Object.entries(routes).map(([id,[label,ic]])=>`<a href="#${id}" class="${v===id?'active':''}" ${v===id?'aria-current="page"':''}><span class="nav-icon">${icon(ic)}</span>${label}</a>`).join('')}</nav>`;}
function render(){
 const v=route();if(!s.pets.some(p=>p.id===s.selected)&&s.selected!=='all')s.selected='all';
 app.innerHTML=`<aside class="sidebar"><a href="#home" class="brand">PawPal<span>一起长大</span></a>${navMarkup(v,'side-nav')}<div class="sidebar-footer">每一段成长，<br>都有人一起见证。<div class="section-divider"></div>V3.0 · 本机交互原型<br>公开案例，私密记录</div></aside><header class="topbar"><a href="#home" class="brand">PawPal<span>一起长大</span></a><div class="top-actions">${ib('查看提醒','notifications','', 'bell').replace('class="icon-btn"','class="icon-btn '+(reminderItems(s).length?'notification-dot':'')+'"')}${ib('个人与家庭设置','settings','','person')}</div></header><div class="content-shell"><div class="pet-switcher" role="group" aria-label="当前宠物"><button class="${s.selected==='all'?'active':''}" data-action="select-pet" data-id="all" aria-pressed="${s.selected==='all'}">${icon('people')}全部宠物</button>${s.pets.map(p=>`<button class="${s.selected===p.id?'active':''}" data-action="select-pet" data-id="${e(p.id)}" aria-pressed="${s.selected===p.id}">${p.cover?`<img class="switch-avatar" src="${e(p.cover)}" alt="">`:`<span class="switch-initial">${e(p.name.slice(0,1))}</span>`}${e(p.name)}</button>`).join('')}</div><main class="page-main" id="main" tabindex="-1">${readError?`<div class="storage-warning" role="alert">${e(readError)}</div>`:''}${({home:()=>home(s),growth:()=>growth(s,ui),health:()=>health(s,ui),discover:()=>discover(s,ui)})[v]()}</main><footer class="app-footer">PawPal｜一起长大 · 每一段成长，都有人一起见证。<br>公开案例照片已筛选；新增照片、健康与互动只保存本机。无云同步。</footer></div>${navMarkup(v,'bottom-nav')}`;
 document.title=`${routes[v][0]} · PawPal｜一起长大`;hydrateMedia(app);
}
async function hydrateMedia(root){for(const img of root.querySelectorAll('img[data-media]')){const id=img.dataset.media;try{if(!mediaUrls.has(id)){const blob=await getBlob(id);if(!blob)throw Error('missing');mediaUrls.set(id,URL.createObjectURL(blob));}if(img.isConnected)img.src=mediaUrls.get(id);}catch{if(img.isConnected){img.replaceWith(Object.assign(document.createElement('div'),{className:'image-placeholder',textContent:'图片暂不可用 · 本机文件缺失'}));}}}}
function openModal(title,body,submit){if(!modal.open)focusBefore=document.activeElement;modalSubmit=submit;modal.innerHTML=`<div class="modal-head"><h2 id="modal-title">${e(title)}</h2>${ib('关闭弹窗','close','','close')}</div><div class="modal-body">${body}</div>`;if(!modal.open)modal.showModal();hydrateMedia(modal);const target=modal.querySelector('[autofocus]')||modal.querySelector('input:not([type=checkbox]),select,textarea')||modal.querySelector('button');target?.focus({preventScroll:true});}
function closeModal(){modal.close();modalSubmit=null;if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}const target=focusBefore?.isConnected?focusBefore:document.querySelector('#main');target?.focus({preventScroll:true});}
modal.addEventListener('cancel',event=>{event.preventDefault();closeModal();});
modal.addEventListener('click',event=>{if(event.target===modal){const r=modal.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeModal();}});
function form(title,fields,onSubmit,label='保存'){openModal(title,`<form id="modal-form"><div class="form-grid">${fields}</div><div class="form-error" role="alert" tabindex="-1"></div><div class="form-footer">${b('取消','close',{kind:'secondary'})}<button class="btn" type="submit">${e(label)}</button></div></form>`,onSubmit);}
const field=(label,name,value='',{type='text',full=false,help='',required=false,max=180,extra=''}={})=>`<label class="field ${full?'full':''}">${e(label)}${type==='textarea'?`<textarea name="${name}" maxlength="${max}" ${required?'required':''} ${extra}>${e(value)}</textarea>`:`<input name="${name}" type="${type}" value="${e(value)}" ${required?'required':''} ${['text','date','month'].includes(type)?`maxlength="${max}"`:''} ${extra}>`}${help?`<span class="form-help">${e(help)}</span>`:''}</label>`;
const select=(label,name,options,value='',full=false)=>`<label class="field ${full?'full':''}">${e(label)}<select name="${name}">${options.map(x=>{const [v,l]=Array.isArray(x)?x:[x,x];return `<option value="${e(v)}" ${String(v)===String(value)?'selected':''}>${e(l)}</option>`;}).join('')}</select></label>`;
const petSelect=id=>select('关联宠物','petId',s.pets.map(p=>[p.id,p.name]),id||currentPet()?.id);
const petChecks=ids=>`<div class="field full"><span>关联宠物（可多选）</span><div class="check-group">${s.pets.map(p=>`<label><input type="checkbox" name="petIds" value="${e(p.id)}" ${ids.includes(p.id)?'checked':''}>${e(p.name)}</label>`).join('')}</div></div>`;
const formError=(f,message)=>{const el=f.querySelector('.form-error');el.textContent=message;el.focus();};
const text=(d,key)=>String(d.get(key)||'').trim();
async function submitModal(event){const f=event.target;if(f.id!=='modal-form'||!modalSubmit)return;event.preventDefault();const submit=f.querySelector('[type=submit]');submit.disabled=true;const label=submit.textContent;submit.textContent='正在保存…';f.querySelector('.form-error').textContent='';try{await modalSubmit(new FormData(f),f);}catch(err){formError(f,err.message||'操作失败，请重试。输入已保留。');}finally{if(submit.isConnected){submit.disabled=false;submit.textContent=label;}}}
modal.addEventListener('submit',submitModal);
function confirm(title,description,onConfirm){form(title,`<p class="confirm-text field full">${e(description)}</p>`,async()=>{if(await onConfirm()){closeModal();toast('操作已完成');}},'确认');}
function showPet(id){const p=s.pets.find(p=>p.id===id);if(p)openModal(p.name+'的档案',petDetail(p));}
function editPet(id){const old=s.pets.find(p=>p.id===id);const p=old||{};form(old?'编辑'+p.name+'的档案':'给新伙伴建档',field('名字','name',p.name,{required:true,max:20})+select('性别','sex',['待确认','母猫','公猫','女孩','男孩'],p.sex||'待确认')+select('宠物类型','species',['猫咪','狗狗','其他宠物'],p.species||'猫咪')+field('品种','breed',p.breed,{help:'未知就写待确认，不以外观推断血统。'})+field('年龄描述','age',p.age,{help:'可以填写“约3岁”；不需要虚构生日。',max:30})+field('毛发特点','fur',p.fur,{max:40})+field('到家月份','arrival',p.arrival?.slice(0,7),{type:'month',help:'仅知月份即可，不会补造具体日期。'})+field('绝育状态','spay',p.spay||'待确认',{max:80})+field('性格标签','tags',(p.tags||[]).join('，'),{full:true,help:'用逗号分隔。'})+field('一句话介绍','bio',p.bio,{full:true,type:'textarea',max:220})+[['相遇故事','story'],['身体特点','body'],['饮食习惯','diet'],['相处边界','boundary'],['互动偏好','interaction']].map(([l,n])=>field(l,n,p[n],{full:true,type:'textarea',max:500})).join(''),async(d,f)=>{const name=text(d,'name');if(!name)return formError(f,'请填写宠物名字。');const arrival=text(d,'arrival');if(arrival&&arrival>today().slice(0,7))return formError(f,'到家月份不能晚于本月。');const pet={...p,id:p.id||uid(),name,sex:text(d,'sex'),species:text(d,'species'),breed:text(d,'breed')||'品种待确认',age:text(d,'age')||'年龄待确认',ageSource:'estimated',fur:text(d,'fur'),arrival,arrivalPrecision:'month',spay:text(d,'spay'),tags:text(d,'tags').split(/[,，]/).map(v=>v.trim()).filter(Boolean).slice(0,8),bio:text(d,'bio'),story:text(d,'story'),body:text(d,'body'),diet:text(d,'diet'),boundary:text(d,'boundary'),interaction:text(d,'interaction'),source:old?.source||'ownerReported',city:s.family.city};if(update(st=>{if(old)st.pets=st.pets.map(x=>x.id===id?pet:x);else{st.pets.push(pet);st.selected=pet.id;}activity(st,`${old?'更新了':'创建了'}${name}的档案`);})){closeModal();toast('档案已保存到本机');}});}
function photoDetail(id){const p=s.photos.find(p=>p.id===id);if(!p)return;openModal(p.title,`<div class="photo-detail-img">${photoImage(p,{large:true})}</div><div class="tags">${(p.tags||[]).map(x=>tag(x)).join('')}${tag(p.source==='library'?'已筛选公开案例':'默认本机私密','subtle')}</div><p style="margin-top:16px">${e(p.description)}</p><dl class="detail-list"><div><dt>关联宠物</dt><dd>${e(petNames(s,p.petIds))}</dd></div><div><dt>拍摄时间</dt><dd>${dateLabel(p.capturedAt)} · ${e(p.capturedSource==='library'?'Apple Photos 记录（含用户调整）':p.capturedAt?'手动填写':'待补充')}</dd></div><div><dt>${p.source==='library'?'导入时间':'上传时间'}</dt><dd>${timeLabel(p.uploadedAt)}</dd></div><div><dt>记录者</dt><dd>${e(p.uploader||'我')}${p.source==='library'?' · 本地相册导入':' · 本机用户'}</dd></div></dl><p class="fine">公开案例资源已存在于公开网站；新增照片仅在本机。下面的分享只进入本机演示社区，不会上传至服务器。</p><div class="detail-action-row">${b('编辑','photo-edit',{id,kind:'secondary',iconName:'edit'})}${b('分享','photo-share',{id,iconName:'share'})}${b('删除','photo-delete',{id,kind:'secondary',iconName:'trash'})}</div>`);}
function editPhoto(id){const p=s.photos.find(p=>p.id===id);const existing=!!p;form(existing?'编辑生活片段':'留下新的生活片段',(existing?'':field('选择照片','photo','',{type:'file',full:true,required:true,extra:'accept="image/jpeg,image/png,image/webp,image/heic,image/heif"',help:'图片只保存本机。支持JPEG、PNG、WebP，最大20 MB；公开分享仍需你主动选择。'})+'<div class="file-preview"></div>')+petChecks(p?.petIds||[currentPet().id])+field('标题','title',p?.title,{full:true,required:true,max:80})+field('拍摄日期','capturedAt',p?.capturedAt?.slice(0,10)||'',{type:'date',full:true,extra:`max="${today()}"`,help:'不知道日期可以留空。上传日期不会替代拍摄日期；手动修改会标记为手动日期。'})+field('描述','description',p?.description,{type:'textarea',full:true,max:1200})+field('标签','tags',p?.tags?.join('，'),{full:true,help:'用逗号分隔；支持按文字搜索。'}),async(d,f)=>{const pets=d.getAll('petIds');if(!pets.length)return formError(f,'请至少选择一只宠物。');const title=text(d,'title');if(!title)return formError(f,'请填写标题。');const capturedAt=text(d,'capturedAt'),err=validDate(capturedAt);if(err)return formError(f,err);let media={};if(!existing){const file=d.get('photo');const result=await optimizeUpload(file);const mediaId=uid();await putBlob(mediaId,result.blob);media={mediaId,width:result.width,height:result.height};}const sameDate=existing&&capturedAt===(p.capturedAt||'').slice(0,10);const photo={...p,...media,id:p?.id||uid(),title,petIds:pets,capturedAt:sameDate?p.capturedAt:capturedAt,capturedSource:sameDate?p.capturedSource:'manual',uploadedAt:p?.uploadedAt||now(),uploader:p?.uploader||'我',description:text(d,'description'),tags:text(d,'tags').split(/[,，]/).map(v=>v.trim()).filter(Boolean).slice(0,10),source:p?.source||'ownerReported',visibility:p?.visibility||'private'};if(update(st=>{if(existing)st.photos=st.photos.map(x=>x.id===id?photo:x);else st.photos.unshift(photo);activity(st,`${existing?'编辑了':'上传了'}「${title}」`);})){closeModal();toast('生活片段已保存到本机');}});}
function editHealth(id,type='weight',petId){const old=s.health.find(h=>h.id===id);const h={...(old||{})};type=h.type||type;const renderForm=()=>form(old?'编辑健康记录':'添加健康记录',petSelect(h.petId||petId)+select('记录类型','type',[['weight','体重'],['vaccine','疫苗'],['deworm','驱虫']],type)+field('发生日期','date',h.date||today(),{type:'date',required:true,extra:`max="${today()}"`})+(type==='weight'?field('实测体重','value',h.value??'',{type:'number',required:true,extra:'min="0.01" max="200" step="0.01"',help:'以kg录入；1kg = 2斤。只记录实际测量。'}):field(type==='vaccine'?'疫苗名称 / 项目':'驱虫药品 / 项目','title',h.title,{help:'不知道名称可留空，不影响记录发生日期。'}))+(type==='weight'?'':field('下次计划日期（可选）','next',h.next,{type:'date',full:true,help:'由你确认日期，不自动推算周期。'}))+field('备注','note',h.note,{type:'textarea',full:true,max:1000}),async(d,f)=>{const date=text(d,'date');let err=validDate(date,{required:true});const next=text(d,'next');err=err||validDate(next,{future:true});if(next&&next<date)err='下次计划不能早于发生日期。';if(err)return formError(f,err);const value=Number(d.get('value'));if(type==='weight'&&(!Number.isFinite(value)||value<=0||value>200))return formError(f,'请输入0.01–200 kg之间的实测体重。');const record={id:h.id||uid(),petId:text(d,'petId'),type,date,value:type==='weight'?value:null,title:type==='weight'?'体重记录':text(d,'title')||(type==='vaccine'?'疫苗接种':'驱虫记录'),next:type==='weight'?'':next,note:text(d,'note'),source:'ownerReported',createdAt:h.createdAt||now(),updatedAt:now()};if(update(st=>{if(old)st.health=st.health.map(x=>x.id===id?record:x);else st.health.unshift(record);activity(st,`${old?'更新':'新增'}了${petNames(st,[record.petId])}的${type==='weight'?'体重':type==='vaccine'?'疫苗':'驱虫'}记录`);})){closeModal();toast('记录已保存，成长时间线同步更新');}});renderForm();modal.querySelector('select[name=type]').addEventListener('change',event=>{const f=event.target.form,d=new FormData(f);h.petId=text(d,'petId');h.date=text(d,'date');h.note=text(d,'note');h.title=text(d,'title');h.next=text(d,'next');h.value=d.get('value')||h.value;type=event.target.value;renderForm();modal.querySelector('select[name=type]').addEventListener('change',onTypeChange);});function onTypeChange(event){const d=new FormData(event.target.form);h.petId=text(d,'petId');h.date=text(d,'date');h.note=text(d,'note');h.title=text(d,'title');h.next=text(d,'next');h.value=d.get('value')||h.value;type=event.target.value;renderForm();modal.querySelector('select[name=type]').addEventListener('change',onTypeChange);}}
function editBehavior(id){const h=s.behaviors.find(x=>x.id===id)||{};form(h.id?'编辑生活观察':'记下生活观察',petSelect(h.petId)+select('观察类别','category',['食欲','睡眠','排泄','宠物互动','异常情况'],h.category||'食欲')+field('观察日期','date',h.date||today(),{type:'date',required:true,extra:`max="${today()}"`})+field('观察内容','note',h.note,{type:'textarea',full:true,required:true,max:1500,help:'描述你看到的情况，不自动判断或诊断。'}),async(d,f)=>{const date=text(d,'date'),err=validDate(date,{required:true});if(err)return formError(f,err);if(!text(d,'note'))return formError(f,'请填写观察内容。');const r={id:h.id||uid(),petId:text(d,'petId'),category:text(d,'category'),date,note:text(d,'note'),source:'ownerReported',createdAt:h.createdAt||now()};if(update(st=>{if(h.id)st.behaviors=st.behaviors.map(x=>x.id===id?r:x);else st.behaviors.unshift(r);activity(st,'记下了'+petNames(st,[r.petId])+'的'+r.category+'观察');})){closeModal();toast('观察已保存到本机');}});}
function editTask(id){const t=s.tasks.find(x=>x.id===id)||{};form(t.id?'编辑照护任务':'安排一件照护小事',petSelect(t.petId)+select('由谁照顾','assignee',s.members.map(m=>[m.id,m.name+'（演示身份）']),t.assignee||'member-0')+field('任务','title',t.title,{full:true,required:true,max:100})+field('计划日期','date',t.date||today(),{type:'date',required:true})+field('备注','note',t.note,{full:true,type:'textarea',max:800,help:'分工只在本机演示，不会通知家庭成员。'}),async(d,f)=>{const date=text(d,'date'),err=validDate(date,{future:true,required:true});if(err)return formError(f,err);if(!text(d,'title'))return formError(f,'请填写任务内容。');const r={...t,id:t.id||uid(),petId:text(d,'petId'),assignee:text(d,'assignee'),date,title:text(d,'title'),note:text(d,'note'),createdAt:t.createdAt||now(),source:'ownerReported'};if(update(st=>{if(t.id)st.tasks=st.tasks.map(x=>x.id===id?r:x);else st.tasks.unshift(r);activity(st,`${t.id?'更新':'创建'}了照护任务「${r.title}」`);})){closeModal();toast('照护任务已保存');}});}
function editEvent(id){const old=s.events.find(x=>x.id===id)||{};form(old.id?'编辑日常':'记一件成长小事',petChecks(old.petIds||[currentPet().id])+field('标题','title',old.title,{full:true,required:true,max:100})+field('发生日期','date',old.date||today(),{type:'date',required:true,extra:`max="${today()}"`})+field('日常记录','description',old.description,{type:'textarea',full:true,max:1000}),async(d,f)=>{const date=text(d,'date'),err=validDate(date,{required:true});if(err)return formError(f,err);if(!d.getAll('petIds').length)return formError(f,'至少选择一只宠物。');if(!text(d,'title'))return formError(f,'请填写标题。');const r={id:old.id||uid(),petIds:d.getAll('petIds'),title:text(d,'title'),date,description:text(d,'description'),type:'daily',createdAt:old.createdAt||now(),source:'ownerReported'};if(update(st=>{if(old.id)st.events=st.events.map(x=>x.id===id?r:x);else st.events.unshift(r);activity(st,'记下了「'+r.title+'」');})){closeModal();toast('小事已加入成长时间线');}});}
function addPost(destination='square',photoId){const p=s.photos.find(x=>x.id===photoId);const pet=s.pets.find(x=>p?.petIds.includes(x.id))||currentPet();form(p?'把这个片段分享出去':destination==='bottle'?'分享宠物漂流瓶':'分享一条宠物日常',(p?`<div class="field full"><div class="photo-detail-img">${photoImage(p)}</div><span class="form-help">关联：${e(petNames(s,p.petIds))}。健康资料不会随照片分享。</span></div>`:petSelect(pet.id)+field('照片（可选）','photo','',{type:'file',full:true,extra:'accept="image/jpeg,image/png,image/webp"',help:'照片只进入本机演示分享池，不会上传到服务器。'})+'<div class="file-preview"></div>')+select('分享到','destination',[['square','宠友广场'],['bottle','宠物漂流瓶'],['both','广场与漂流瓶']],destination)+select('话题','topic',topics,topics[0])+field('城市','city',s.family.city,{required:true,max:20,help:'只写城市，不写具体住址。'})+field('标题','title',p?.title||'',{full:true,required:true,max:100})+field('想说的话','text',p?.description||'',{type:'textarea',full:true,required:true,max:1500})+`<label class="share-check"><input type="checkbox" name="confirmShare" required><span>我已检查照片和文字，愿意将它放入本机的社区演示池。原型没有后台，其他设备看不到这次分享；请避免放入人脸、证件或地址。</span></label>`,async(d,f)=>{if(!d.get('confirmShare'))return formError(f,'请确认分享范围。');if(!text(d,'title')||!text(d,'text')||!text(d,'city'))return formError(f,'请填写标题、正文和城市。');let image={};if(p)image={image:p.image||p.src,mediaId:p.mediaId,width:p.width,height:p.height};else{const file=d.get('photo');if(file?.size){const result=await optimizeUpload(file),id=uid();await putBlob(id,result.blob);image={mediaId:id,width:result.width,height:result.height};}}const petId=p?.petIds[0]||text(d,'petId');const post={id:uid(),petIds:p?.petIds||[petId],petName:petNames(s,p?.petIds||[petId]),species:s.pets.find(t=>t.id===petId)?.species||'猫咪',city:text(d,'city'),title:text(d,'title'),text:text(d,'text'),topic:text(d,'topic'),destination:text(d,'destination'),date:today(),createdAt:now(),source:'ownerReported',ownerId:'local-user',own:true,comments:[],photoId:p?.id||'',...image};if(update(st=>{st.posts.unshift(post);activity(st,'分享了「'+post.title+'」（本机演示）');})){closeModal();ui.discoverTab=post.destination==='bottle'?'bottle':'square';ui.bottleIndex=0;if(route()!=='discover')location.hash='discover';else render();toast('已加入本机分享池');}},'确认分享');}
function postDetail(id){const p=s.posts.find(x=>x.id===id);if(!p)return;openModal(p.title,`${p.image||p.mediaId?`<div class="photo-detail-img">${photoImage(p,{large:true})}</div>`:''}<div class="tags">${tag(p.petName||petNames(s,p.petIds))}${tag(p.city)}${tag(p.source==='demo'?'演示内容':p.own?'本机分享':'公开案例','subtle')}</div><p style="margin-top:18px">${e(p.text)}</p><p class="fine">日期 ${dateLabel(p.date)} · 评论与互动只保存本机，不会发送给作者。</p><div class="detail-action-row">${b(s.liked.includes(id)?'取消喜欢':'喜欢','post-like',{id,kind:'secondary',iconName:'heart'})}${b(s.saved.includes(id)?'取消收藏':'收藏','post-save',{id,kind:'secondary',iconName:'bookmark'})}${b('更多','post-options',{id,kind:'secondary',iconName:'more'})}</div><div class="section-divider"></div><h3>本机评论 · ${p.comments?.length||0}</h3><div class="comment-list">${p.comments?.length?p.comments.map(c=>`<p><strong>${e(c.author)} · ${c.source==='demo'?'演示':'本机'}</strong><br>${e(c.text)}${c.id&&c.source!=='demo'?ib('删除本机评论','comment-delete',id+':'+c.id,'trash'):''}</p>`).join(''):'<p class="fine">还没有本机评论。留下一句对宠物的善意。</p>'}</div><form class="comment-form" data-post="${e(id)}"><input name="comment" aria-label="评论内容" placeholder="只保存本机，不发送" maxlength="300" required><button type="submit" class="btn">评论</button></form>`);}
function postOptions(id){const p=s.posts.find(x=>x.id===id);if(!p)return;openModal('内容选项',`<p class="fine">举报与屏蔽为本机原型操作，不会送交真实审核团队。</p><div class="settings-links">${b('举报并隐藏这条内容','post-report',{id,kind:'secondary'})}${b('屏蔽该演示发布者','post-block',{id,kind:'secondary'})}${p.own?b('删除我的本机分享','post-delete',{id,kind:'secondary',iconName:'trash'}):''}</div>`);}
function showSettings(){openModal('个人与家庭',`<div class="local-badge"><h3>${e(s.family.name)}</h3><p class="fine">${e(s.family.city)} · ${e(s.family.district)} · ${s.members.length} 位成员</p></div><div class="member-list">${s.members.map(m=>`<div><span class="member-avatar">${e(m.initial)}</span><span>${e(m.name)}<small>演示身份 · 无实际账号或远程协作</small></span></div>`).join('')}</div><div class="notice">${icon('lock')}新增照片和健康记录默认本机私密。此原型没有账号权限系统或家庭云同步。公开案例图片属于网站公开资源。</div><div class="settings-links">${b('编辑家庭与演示成员','family-edit',{kind:'secondary',iconName:'edit'})}${b('导出本机记录（含上传图片）','export',{kind:'secondary',iconName:'download'})}${s.legacyAvailable?b('导出保留的旧版记录','legacy-export',{kind:'secondary',iconName:'download'}):''}${b('恢复被举报 / 屏蔽的内容','moderation-reset',{kind:'secondary'})}${b('隐私与原型说明','privacy',{kind:'secondary',iconName:'lock'})}</div><p class="fine" style="margin-top:18px">记录保存在当前浏览器与设备；清理网站数据会丢失记录。导出文件包含你自己的私密数据，请自行保管。</p>`);}
function editFamily(){form('家庭与演示成员',field('家庭名称','name',s.family.name,{required:true,full:true,max:60})+field('城市','city',s.family.city,{required:true,max:20})+field('区域','district',s.family.district,{max:20})+s.members.map(m=>field('演示成员'+(Number(m.id.split('-')[1])+1),'m-'+m.id,m.name,{max:20,help:m.id==='member-0'?'当前本机操作者。不建立账号或发送邀请。':''})).join(''),async(d,f)=>{if(!text(d,'name')||!text(d,'city'))return formError(f,'请填写家庭名称与城市。');if(update(st=>{st.family={name:text(d,'name'),city:text(d,'city'),district:text(d,'district')};st.members=st.members.map(m=>({...m,name:text(d,'m-'+m.id)||m.name,initial:(text(d,'m-'+m.id)||m.name).slice(0,1)}));activity(st,'更新了家庭设置');})){closeModal();toast('家庭设置已保存到本机');}});}
function downloadJson(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exportData(){toast('正在准备本机导出…');try{const ids=[...new Set([...s.photos,...s.posts].map(p=>p.mediaId).filter(Boolean))];const media=await allMedia(ids);downloadJson({exportedAt:now(),format:'pawpal-v3',state:s,media,missingMedia:ids.filter(id=>!media[id])},'pawpal-local-'+today()+'.json');toast('已导出本机记录，请保管好私密文件');}catch{toast('导出图片失败，已导出结构化记录。请检查本机图片存储。');downloadJson({exportedAt:now(),state:s,mediaExportFailed:true},'pawpal-records-'+today()+'.json');}}
function deleteItem(collection,id,label){const item=s[collection].find(x=>x.id===id);if(!item)return;confirm('删除'+label,`将从本机移除这条${label}。${collection==='photos'?'已分享的副本会保留；公开案例资源不会从网站删除。':''}此操作不可撤销。`,()=>update(st=>{st[collection]=st[collection].filter(x=>x.id!==id);activity(st,'删除了一条'+label);}));}
const handlers={
 close:()=>closeModal(),'select-pet':id=>update(st=>st.selected=id),settings:showSettings,
 notifications:()=>openModal('计划提醒',reminderItems(s).length?`<div class="reminders">${reminderItems(s).map(r=>`<p>${icon('bell')}<span>${e(r.title)}<small>${dateLabel(r.date)} · ${e(r.label)}</small></span></p>`).join('')}</div>${b('管理健康与照护','go-health',{kind:'secondary'})}`:empty('没有计划提醒','设置下一次日期或安排照护后，这里会显示。',b('安排照护','task-add',{kind:'secondary'}))),
 'pet-detail':showPet,'pet-add':()=>editPet(),'pet-edit':editPet,
 'go-growth':()=>{if(modal.open)closeModal();location.hash='growth';},'go-health':()=>{if(modal.open)closeModal();location.hash='health';},
 'photo-add':()=>editPhoto(),'photo-detail':photoDetail,'photo-edit':editPhoto,'photo-delete':id=>deleteItem('photos',id,'照片'),'photo-share':id=>addPost('square',id),
 'growth-mode':id=>{ui.growthMode=id;render();},'growth-clear':()=>{ui.growthSearch='';ui.growthDate='';render();},'event-filter':id=>{ui.eventType=id;render();},'event-add':()=>editEvent(),'event-edit':editEvent,'event-delete':id=>deleteItem('events',id,'成长日常'),
 'health-add':()=>editHealth(),'health-weight':id=>editHealth(undefined,'weight',id),'health-edit':id=>editHealth(id),'health-delete':id=>deleteItem('health',id,'健康记录'),'health-filter':id=>{ui.healthType=id;render();},unit:id=>update(st=>st.settings.unit=id),
 'behavior-add':()=>editBehavior(),'behavior-edit':editBehavior,'behavior-delete':id=>deleteItem('behaviors',id,'生活观察'),
 'task-add':()=>editTask(),'task-edit':editTask,'task-delete':id=>deleteItem('tasks',id,'照护任务'),'task-toggle':id=>{const t=s.tasks.find(x=>x.id===id);if(!t)return;if(update(st=>{const r=st.tasks.find(x=>x.id===id);r.completedAt=r.completedAt?null:now();activity(st,`${r.completedAt?'完成':'撤销完成'}了照护「${r.title}」`,'ownerReported',st.members.find(m=>m.id===r.assignee)?.name+'（演示身份）');}))toast(t.completedAt?'已撤销完成':'照护已完成，时间线已更新');},
 'discover-tab':id=>{ui.discoverTab=id;render();},'bottle-next':()=>{const count=visiblePosts(s).filter(p=>p.destination==='bottle'||p.destination==='both'||p.source==='demo'||p.source==='library').length;ui.bottleIndex=count>1?(ui.bottleIndex+1+Math.floor(Math.random()*(count-1)))%count:0;render();},'bottle-feedback':(id,el)=>{if(update(st=>st.bottleFeedback[id]=st.bottleFeedback[id]===el.dataset.value?null:el.dataset.value))toast('善意已记录在本机');},
 'post-add':()=>addPost(),'post-add-bottle':()=>addPost('bottle'),'post-detail':postDetail,'post-options':postOptions,'post-like':id=>{if(update(st=>st.liked=st.liked.includes(id)?st.liked.filter(x=>x!==id):[...st.liked,id])){if(modal.open)postDetail(id);}},'post-save':id=>{if(update(st=>st.saved=st.saved.includes(id)?st.saved.filter(x=>x!==id):[...st.saved,id])){if(modal.open)postDetail(id);toast(s.saved.includes(id)?'已收藏到本机':'已取消收藏');}},
 'post-report':id=>confirm('举报并隐藏','此操作只在本机隐藏该内容，不会送交真实审核。可在设置里恢复。',()=>update(st=>st.reported.push(id))),
 'post-block':id=>{const p=s.posts.find(x=>x.id===id);confirm('屏蔽演示发布者','将隐藏这个演示发布者的内容。只影响本机，可在设置里恢复。',()=>update(st=>{if(p&&!st.blocked.includes(p.ownerId))st.blocked.push(p.ownerId);}));},
 'post-delete':id=>deleteItem('posts',id,'本机分享'),'saved-filter':()=>{ui.onlySaved=!ui.onlySaved;render();},
 'comment-delete':id=>{const [postId,commentId]=id.split(':');confirm('删除评论','删除这条只保存在本机的评论。',()=>update(st=>{const p=st.posts.find(p=>p.id===postId);if(p)p.comments=p.comments.filter(c=>c.id!==commentId);}));},
 'local-clear':()=>{ui.localCity='';ui.localDistrict='';ui.localSpecies='全部';ui.localType='';render();},'resource-detail':id=>{const r=localContents.find(x=>x.id===id);if(r)openModal(r.title,`${tag('演示 · 未核实','warm')}<p style="margin-top:18px">${e(r.detail)}</p><p class="fine">${e(r.city)} · ${e(r.district)} · ${e(r.type)}</p>${b(s.resourceSaved.includes(id)?'取消本机收藏':'收藏到本机','resource-save',{id,kind:'secondary',iconName:'bookmark'})}`);},'resource-save':id=>{if(update(st=>st.resourceSaved=st.resourceSaved.includes(id)?st.resourceSaved.filter(x=>x!==id):[...st.resourceSaved,id])){toast(s.resourceSaved.includes(id)?'资源已收藏到本机':'已取消收藏');if(modal.open)handlers['resource-detail'](id);}},
 'family-edit':editFamily,export:exportData,'legacy-export':()=>{try{downloadJson(JSON.parse(localStorage.getItem('pawpal-v1')),'pawpal-v1-preserved.json');toast('旧版原始记录已导出');}catch{toast('旧版数据无法解析，原始内容仍保留');}},'moderation-reset':()=>{if(update(st=>{st.reported=[];st.blocked=[];})){closeModal();toast('已恢复隐藏内容');}},
 privacy:()=>openModal('隐私与原型边界',`<ul class="help-list"><li>网站公开案例：两只猫的主人提供资料及经筛选照片，所有访问者可见。</li><li>你新增的照片存在 IndexedDB，档案、健康、任务与互动存在当前浏览器的 LocalStorage。</li><li>“家庭私密”表示不加入本机分享池；没有服务器账号验证或家庭访问控制。</li><li>分享、评论、举报与协作均为本机原型演示，不会上传或通知其他人。</li><li>上传图片在本机缩小并重新编码，移除原始图片元数据；拍摄日期由你填写，可留空。</li><li>照片库原件和精确地理位置没有加入公开仓库。既有公开案例资源不能通过本机删除从服务器移除。</li><li>导出后请自行保管文件；清理浏览器数据会失去未导出的记录。</li></ul>`)
};
document.addEventListener('click',event=>{if(event.target.closest('.skip-link')){event.preventDefault();document.querySelector('#main').focus();return;}const el=event.target.closest('[data-action]');if(!el||el.disabled)return;if(!s.pets.length&&['photo-add','health-add','task-add','behavior-add','event-add','post-add','post-add-bottle'].includes(el.dataset.action)){openModal('先给伙伴建个档案',empty('还没有宠物档案','建立档案后，照片与健康记录才能归属于正确的伙伴。',b('添加宠物','pet-add',{kind:'secondary'})));return;}const handler=handlers[el.dataset.action];if(handler)handler(el.dataset.id,el);});
document.addEventListener('submit',event=>{const f=event.target;if(f.id==='modal-form')return;
 if(f.id==='growth-search'){event.preventDefault();const d=new FormData(f);ui.growthSearch=text(d,'search');ui.growthDate=text(d,'month');render();}
 if(f.id==='square-filter'){event.preventDefault();const d=new FormData(f);ui.species=text(d,'species');ui.topic=text(d,'topic');ui.city=text(d,'city');render();}
 if(f.id==='local-filter'){event.preventDefault();const d=new FormData(f);ui.localCity=text(d,'city');ui.localDistrict=text(d,'district');ui.localSpecies=text(d,'species');ui.localType=text(d,'type');render();}
 if(f.classList.contains('comment-form')){event.preventDefault();const content=text(new FormData(f),'comment');if(!content)return toast('请填写评论内容');const id=f.dataset.post;if(update(st=>{const p=st.posts.find(x=>x.id===id);if(p){p.comments.push({id:uid(),author:'我',text:content,source:'ownerReported',createdAt:now()});}})){postDetail(id);toast('评论只保存本机');}}
});
document.addEventListener('change',event=>{const input=event.target;if(input.type==='file'&&input.files[0]){const preview=modal.querySelector('.file-preview');if(!preview)return;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(input.files[0]);preview.innerHTML=`<img src="${previewUrl}" alt="待上传图片预览">`;}if(input.name==='city'&&input.form?.id==='local-filter'){const district=input.form.querySelector('[name=district]');district.innerHTML='<option value="">所有区域</option>'+[...new Set(localContents.filter(r=>!input.value||r.city===input.value).map(r=>r.district))].map(d=>`<option>${e(d)}</option>`).join('');}});
window.addEventListener('hashchange',()=>{if(modal.open)closeModal();render();window.scrollTo(0,0);document.querySelector('#main').focus({preventScroll:true});});
window.addEventListener('storage',event=>{if(event.key==='pawpal-v3'){const fresh=load();if(!fresh.error){s=fresh.state;render();toast('本机另一个页面的记录已更新');}}});
render();
