import {today,esc as e,dateLabel,button as b,icon} from './utils.js?v=3.2.0';
export const deviceDefinitions=[
 {id:'litter',name:'智能猫砂盆',kind:'toilet',icon:'health',capabilities:'个体识别、大小便分类、使用时长、体重',assumption:'假设支持个体识别与称重；每次记录均为模拟。'},
 {id:'feeder',name:'智能喂食器',kind:'food',icon:'note',capabilities:'个体识别、投粮量、实际进食量',assumption:'假设支持个体识别与进食量测量，投粮量与实际进食量分开记录。'},
 {id:'water',name:'智能饮水机',kind:'water',icon:'deworm',capabilities:'个体识别、饮水时间、饮水量',assumption:'假设支持个体识别与饮水量测量，不以设备总用水量推算个体饮水。'}
];
export const shiftDay=(date,n)=>new Date(Date.parse(date+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
export function simulation(anchor=today()){
 const events=[];
 for(let offset=-89;offset<=0;offset++){const date=shiftDay(anchor,offset),day=offset+89;
 for(const [pi,petId] of ['erduo','weiba'].entries()){
 const variation=((day*7+pi*3)%11)-5,food=(pi===0?64:55)+variation-(pi===0&&offset>=-6?9:0),water=(pi===0?182:205)+variation*3;
 for(const [j,time] of ['07:30','13:10','19:00'].entries()){const consumed=j===2?food-Math.round(food*.3)-Math.round(food*.35):Math.round(food*(j===0?.3:.35));events.push({id:`sim-${date}-${petId}-food-${j}`,petId,deviceId:'feeder',kind:'food',at:`${date}T${time}:00+08:00`,dispensed:30,consumed,source:'simulated',note:''});}
 for(const [j,time] of ['08:15','12:20','16:40','21:10'].entries()){const volume=j===3?water-3*Math.floor(water/4):Math.floor(water/4);events.push({id:`sim-${date}-${petId}-water-${j}`,petId,deviceId:'water',kind:'water',at:`${date}T${time}:00+08:00`,volume,source:'simulated',note:''});}
 for(const [j,time] of ['06:42','09:42','18:35'].entries()){events.push({id:`sim-${date}-${petId}-toilet-${j}`,petId,deviceId:'litter',kind:'toilet',at:`${date}T${time}:00+08:00`,classification:j===2?'大便':'小便',duration:38+((day+pi*9+j*5)%25),weight:Number(((pi===0?3.52:5.02)+Math.sin(day/9)*.025+j*.005).toFixed(2)),source:'simulated',note:''});}
 }}
 // Today's unfinished day contains only events at or before the current Shanghai time.
 const now=Date.now();return {simulationAnchor:anchor,deviceEvents:events.filter(x=>Date.parse(x.at)<=now),devices:deviceDefinitions.map(x=>({...x,status:'simulated-connected',source:'simulated'}))};
}
export function petEvents(s,petId){return (s.deviceEvents||[]).filter(x=>s.space==='experience'&&x.source==='simulated'&&x.petId===petId&&s.pets.some(p=>p.id===petId));}
export function series(s,petId,metric,days=7,end=today()){
 const rows=petEvents(s,petId);return Array.from({length:days},(_,i)=>{const date=shiftDay(end,i-days+1),events=rows.filter(x=>x.at.slice(0,10)===date),matching=events.filter(x=>x.kind===(metric==='weight'?'toilet':metric));let value=null,source='simulated';
 if(metric==='weight'){const manual=s.health.filter(x=>x.petId===petId&&x.type==='weight'&&x.date===date).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];if(manual){value=manual.value;source='manual';}else if(matching.length)value=matching.at(-1).weight;}
 else if(matching.length)value=matching.reduce((n,x)=>n+(metric==='food'?x.consumed:metric==='water'?x.volume:1),0);
 return {date,value,source,events:matching};});
}
export function currentWeight(s,p){const manual=s.health.filter(x=>x.petId===p.id&&x.type==='weight').sort((a,b)=>b.date.localeCompare(a.date)||String(b.createdAt).localeCompare(String(a.createdAt)))[0],event=petEvents(s,p.id).filter(x=>x.kind==='toilet').sort((a,b)=>b.at.localeCompare(a.at))[0];if(manual&&(!event||manual.date>=event.at.slice(0,10)))return {value:manual.value,date:manual.date,label:'手动测量',source:'manual'};if(event)return {value:event.weight,date:event.at.slice(0,10),label:'设备模拟',source:'simulated'};return {value:p.weightEstimate||null,date:null,label:p.weightEstimate?'估算 · 日期未知':'尚未记录',source:'estimated'};}
export function daySummary(s,petId,date=today()){const x=petEvents(s,petId).filter(x=>x.at.slice(0,10)===date);return {food:x.filter(x=>x.kind==='food').reduce((n,x)=>n+x.consumed,0),water:x.filter(x=>x.kind==='water').reduce((n,x)=>n+x.volume,0),toilet:x.filter(x=>x.kind==='toilet').length,hasFood:x.some(x=>x.kind==='food'),hasWater:x.some(x=>x.kind==='water'),hasToilet:x.some(x=>x.kind==='toilet')};}
export const metricNames={weight:'体重',food:'进食',water:'饮水',toilet:'如厕'};
export const metricUnits={weight:'kg',food:'g',water:'ml',toilet:'次'};
export function trendNotice(s,petId){const before=series(s,petId,'food',7,shiftDay(today(),-8)),recent=series(s,petId,'food',7,shiftDay(today(),-1));if(before.some(x=>x.value===null)||recent.some(x=>x.value===null))return null;const avg=rs=>rs.reduce((n,x)=>n+x.value,0)/rs.length,a=avg(before),z=avg(recent);return z<a*.95?{before:a,recent:z,percent:Math.round((a-z)/a*100),from:shiftDay(today(),-7),to:shiftDay(today(),-1)}:null;}
export function metricsStrip(s,p,action='health-open'){
 const d=daySummary(s,p.id),w=currentWeight(s,p);return `<div class="daily-metrics">${[['food','今日进食',d.hasFood?d.food:'—','g'],['water','今日饮水',d.hasWater?d.water:'—','ml'],['toilet','今日如厕',d.hasToilet?d.toilet:'—','次'],['weight','最近体重',w.value===null?'—':Number((w.value*(s.settings.unit==='斤'?2:1)).toFixed(2)),s.settings.unit]].map(([metric,label,value,unit])=>`<button data-action="${action}" data-id="${p.id}:${metric}" aria-label="查看${e(p.name)}${label}"><span>${label}</span><strong>${metric==='weight'&&w.source==='estimated'&&value!=='—'?'约':''}${value}<small>${unit}</small></strong><em>${metric==='weight'?w.label:d['has'+metric[0].toUpperCase()+metric.slice(1)]?'截至现在':'未连接设备'}</em></button>`).join('')}</div>`;
}
export function chart(s,petId,metric,days,selectedDate){const factor=metric==='weight'&&s.settings.unit==='斤'?2:1,rows=series(s,petId,metric,days).map(r=>({...r,value:r.value===null?null:Number((r.value*factor).toFixed(2))})),points=rows.filter(x=>x.value!==null),unit=metric==='weight'?s.settings.unit:metricUnits[metric];
 if(!points.length)return `<div class="chart-empty">${metric==='weight'?'还没有实测记录。记下第一次称重，慢慢看变化。':'设备未连接，暂时没有'+metricNames[metric]+'记录。'}</div>`;
 const width=640,height=210,left=44,right=616,top=25,bottom=160,min=metric==='weight'?Math.min(...points.map(x=>x.value))-.08:0,max=metric==='weight'?Math.max(...points.map(x=>x.value))+.08:Math.max(...points.map(x=>x.value))*1.15,range=max-min||1;
 const x=i=>left+i/Math.max(1,days-1)*(right-left),y=v=>bottom-(v-min)/range*(bottom-top);
 const segments=[];let seg=[];rows.forEach((r,i)=>{if(r.value===null){if(seg.length)segments.push(seg);seg=[];}else seg.push([x(i),y(r.value)]);});if(seg.length)segments.push(seg);
 const selected=rows.find(r=>r.date===selectedDate)||points.at(-1);
 return `<div class="interactive-chart"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="最近${days}天${metricNames[metric]}趋势，单位${unit}">${[0,.5,1].map(v=>`<path class="chart-grid" d="M${left} ${top+(bottom-top)*v}H${right}"/><text x="0" y="${top+(bottom-top)*v+4}">${(max-range*v).toFixed(metric==='weight'?2:0)}</text>`).join('')}${metric==='weight'?segments.filter(p=>p.length>1).map(p=>`<polyline points="${p.map(v=>v.join(',')).join(' ')}"/>`).join(''):rows.filter(r=>r.value!==null).map(r=>`<rect class="chart-bar" x="${x(rows.indexOf(r))-Math.min(8,200/days)}" y="${y(r.value)}" width="${Math.min(16,400/days)}" height="${bottom-y(r.value)}" rx="2"/>`).join('')}${rows.map((r,i)=>r.value===null?'':`<g data-action="chart-point" data-id="${r.date}" tabindex="0" role="button" aria-label="${r.date}，${r.value}${unit}"><circle class="chart-hit" cx="${x(i)}" cy="${y(r.value)}" r="15"/><circle class="chart-dot ${selected.date===r.date?'selected':''}" cx="${x(i)}" cy="${y(r.value)}" r="${metric==='weight'?4:2.5}"/><title>${r.date} · ${r.value}${unit}</title></g>`).join('')}<text x="${left}" y="197">${rows[0].date.slice(5)}</text><text x="${right}" y="197" text-anchor="end">${rows.at(-1).date.slice(5)}</text></svg><div class="chart-readout" aria-live="polite"><span>${dateLabel(selected.date)}</span><strong>${selected.value} ${unit}</strong><span>${selected.source==='manual'?'手动测量':'设备模拟'}${selected.date===today()?' · 今日累计':''}</span></div><label class="chart-date">查看某一天<select id="chart-date" aria-label="选择趋势日期">${points.map(r=>`<option value="${r.date}" ${r.date===selected.date?'selected':''}>${dateLabel(r.date)} · ${r.value} ${unit}</option>`).join('')}</select></label>${metric==='weight'&&points.length===1?'<p class="fine">只有一次测量，暂不连成趋势线。</p>':''}</div>`;
}
export function eventLabel(x){return x.kind==='food'?`进食 ${x.consumed} g`:x.kind==='water'?`饮水 ${x.volume} ml`:`${x.classification} · ${x.duration} 秒`;}
export function eventRows(s,petId,metric='all',date=''){return petEvents(s,petId).filter(x=>(metric==='all'||metric==='weight'&&x.kind==='toilet'||x.kind===metric)&&(!date||x.at.startsWith(date))).sort((a,b)=>b.at.localeCompare(a.at));}
export function eventList(events,limit=12){return `<div class="device-event-list">${events.slice(0,limit).map(x=>`<button data-action="device-event" data-id="${x.id}" class="device-event"><span class="event-time">${x.at.slice(11,16)}<small>${x.at.slice(5,10).replace('-','/')}</small></span><span><strong>${eventLabel(x)}</strong><small>${deviceDefinitions.find(d=>d.id===x.deviceId)?.name}${x.note?' · '+e(x.note):''}</small></span><span class="event-weight">${x.kind==='toilet'?x.weight+' kg':x.kind==='food'?'投粮 '+x.dispensed+' g':''}${icon('arrow')}</span></button>`).join('')}</div>`;}
