import {esc as e,icon,button as b,iconButton as ib,tag,empty,dateLabel,timeLabel,matchPet,sortDated,sourceLabel,today} from './utils.js';
import {milestones,localContents,topics} from './data.js';
export const petNames=(s,ids)=>(ids||[]).map(id=>s.pets.find(p=>p.id===id)?.name||'未知宠物').join('、');
export function photoImage(p,{large=false,alt='',eager=false}={}){
 const url=large?(p.large||p.image||p.src):(p.image||p.src||p.thumb);
 return url?`<img src="${e(url)}" ${p.thumb&&p.large?`srcset="${e(p.thumb)} 400w, ${e(p.image)} 1000w, ${e(p.large)} 1600w" sizes="(max-width: 600px) 48vw, 500px"`:''} alt="${e(alt||p.title||'宠物照片')}" loading="${eager?'eager':'lazy'}" decoding="async" ${p.width&&p.height?`width="${p.width}" height="${p.height}"`:''}>`:p.mediaId?`<img data-media="${e(p.mediaId)}" alt="${e(alt||p.title||'上传的宠物照片')}" loading="lazy">`:`<div class="image-placeholder">${icon('growth')}<span>还没有照片</span></div>`;
}
export const avatar=p=>p.cover||p.coverMediaId?`<img class="pet-avatar" ${p.cover?`src="${e(p.cover)}"`:`data-media="${e(p.coverMediaId)}"`} alt="${e(p.name)}">`:`<span class="pet-avatar initials">${e(p.name.slice(0,1))}</span>`;
export const heading=(kicker,title,text,action='')=>`<div class="page-heading"><div><p class="eyebrow">${e(kicker)}</p><h1>${e(title)}</h1>${text?`<p class="lead">${e(text)}</p>`:''}</div>${action}</div>`;
export function home(s){
 const pets=s.pets.filter(p=>s.selected==='all'||p.id===s.selected);const photos=s.photos.filter(p=>matchPet(p,s.selected)).sort(sortDated);
 const recent=photos.slice(0,3);const tasks=s.tasks.filter(t=>!t.completedAt&&matchPet(t,s.selected)).slice(0,3);const reminders=reminderItems(s).slice(0,3);
 return `<section class="family-intro"><div class="intro-copy"><p class="eyebrow">OUR LITTLE FAMILY</p><h1>${e(s.family.name)}</h1><p class="lead">每一段成长，<br class="mobile-only">都有人一起见证。</p><div class="family-row"><div class="member-stack">${s.members.map(m=>`<span title="${e(m.name)} · 演示身份">${e(m.initial)}</span>`).join('')}</div><span>${s.members.length} 位家人 · ${s.pets.length} 只宠物</span></div><p class="fine">家庭人数为真实资料，成员身份为演示。</p></div><div class="family-quote"><span class="quote-mark">“</span><p>普通的一天，<br>也值得好好记住。</p><span>一起吃饭 · 一起玩耍 · 一起长大</span></div></section>
 <div class="section-title"><h2>今天，和谁一起？</h2>${b('添加宠物','pet-add',{kind:'text',iconName:'plus'})}</div>
 ${!pets.length?empty('还没有宠物档案','从名字开始，慢慢记录新伙伴的生活。',b('添加宠物','pet-add',{kind:'secondary'})):''}<div class="pet-grid">${pets.map(p=>`<article class="pet-card"><button class="pet-photo" data-action="pet-detail" data-id="${e(p.id)}" aria-label="查看${e(p.name)}档案">${p.cover||p.coverMediaId?photoImage({image:p.cover,mediaId:p.coverMediaId,title:p.name},{eager:true}):photoImage({})}<span class="photo-label">${e(p.name)} ${icon('arrow')}</span></button><div class="pet-info"><div class="pet-meta">${e(p.sex)} · ${e(p.age)} <span class="fine">${p.ageSource==='estimated'?'估算':''}</span></div><p class="pet-breed">${e(p.breed)}</p><p>${e(p.bio)}</p><div class="tags">${(p.tags||[]).map(x=>tag(x)).join('')}</div></div></article>`).join('')}</div>
 <div class="quick-actions">${b('留下新照片','photo-add',{iconName:'growth'})}${b('记录健康','health-add',{iconName:'health'})}${b('安排照护','task-add',{iconName:'check'})}</div>
 ${s.pets.some(p=>p.id==='weiba')&&s.pets.some(p=>p.id==='erduo')?`<section class="relationship"><span class="eyebrow">BETTER TOGETHER</span><h2>家里的两位跑酷搭档</h2><p>尾巴陪耳朵追逐玩耍，彼此相处融洽。我们叫她们“两姐妹”，是生活里的称呼。</p><div class="tags">${tag('追逐跑酷')}${tag('相处融洽')}${tag('非已知血缘关系','subtle')}</div></section>`:''}
 <div class="home-columns"><section><div class="section-title"><h2>一起照顾的小事</h2>${b('查看健康','go-health',{kind:'text',iconName:'arrow'})}</div>${tasks.length?tasks.map(t=>taskCard(t,s)).join(''):empty('今天没有待办照护','可以独自记录，也可以用演示成员分配一件小事。',b('创建照护任务','task-add',{kind:'secondary',iconName:'plus'}))}${reminders.length?`<div class="reminders">${reminders.map(r=>`<p>${icon('bell')}<span>${e(r.title)}<small>${e(r.date)} · ${e(r.label)}</small></span></p>`).join('')}</div>`:''}</section><section><div class="section-title"><h2>家庭动态</h2>${b('家庭设置','settings',{kind:'text',iconName:'arrow'})}</div>${s.activity.length?`<div class="activity-list">${s.activity.slice(0,5).map(a=>`<div><span class="activity-dot"></span><p>${e(a.text)}<small>${e(a.actor||'我')} · ${timeLabel(a.createdAt)} · ${e(sourceLabel[a.source]||'本机操作')}</small></p></div>`).join('')}</div>`:empty('从下一条记录开始','上传照片或完成照护后，这里会留下真实的本机操作。')}</section></div>
 <div class="section-title"><h2>最近的生活片段</h2>${b('打开相册','go-growth',{kind:'text',iconName:'arrow'})}</div>${recent.length?`<div class="recent-grid">${recent.map(p=>photoCard(p,s)).join('')}</div>`:empty('相册还在等第一张照片','照片默认只保存在本机；分享由你决定。',b('上传照片','photo-add',{kind:'secondary'}))}`;
}
export function petDetail(p,s){const measured=s?.health.filter(h=>h.petId===p.id&&h.type==='weight').sort(sortDated)[0];return `<div class="pet-detail-cover">${p.cover||p.coverMediaId?photoImage({image:p.cover,mediaId:p.coverMediaId,title:p.name},{large:true}):photoImage({})}</div><div class="tags">${tag(p.sex)}${tag(p.age+' · '+(p.ageSource==='estimated'?'估算':'主人填写'))}${tag(p.fur||'毛发待确认')}</div><p class="detail-bio">${e(p.bio)}</p><dl class="detail-list"><div><dt>品种</dt><dd>${e(p.breed)}</dd></div><div><dt>来到家里</dt><dd>${dateLabel(p.arrival)}${p.arrivalPrecision==='month'?' · 仅知月份':''}</dd></div><div><dt>当前体重</dt><dd>${measured?`${measured.value} kg / ${measured.value*2} 斤 · 实测，${dateLabel(measured.date)}`:p.weightEstimate?`约 ${p.weightEstimate} kg / ${p.weightEstimate*2} 斤 · 主人估算，测量日期未知`:'待记录'}</dd></div><div><dt>绝育状态</dt><dd>${e(p.spay||'待确认')}</dd></div></dl><div class="detail-sections">${[['相遇的故事',p.story],['身体特点',p.body],['吃饭习惯',p.diet],['相处与边界',p.boundary],['家里的日常',p.interaction]].map(([h,t])=>`<section><h3>${e(h)}</h3><p>${e(t||'待补充')}</p></section>`).join('')}</div>${p.id==='erduo'?`<p class="notice">主人对血统有猜测，但未经证实，不作为品种信息。发现时有耳螨；治疗及恢复信息待确认。</p>`:''}${b('编辑档案','pet-edit',{id:p.id,kind:'secondary',iconName:'edit'})}`;}
export function photoCard(p,s){return `<article class="photo-card"><button data-action="photo-detail" data-id="${e(p.id)}" class="photo-open" aria-label="查看照片：${e(p.title)}">${photoImage(p)}<span class="photo-card-meta"><strong>${e(p.title)}</strong><span>${e(petNames(s,p.petIds))} · ${dateLabel(p.capturedAt)}</span></span></button><span class="privacy-label">${p.source==='library'?'公开案例':icon('lock')+'本机私密'}</span></article>`;}
export function timelineItems(s){const arrivals=s.pets.filter(p=>p.arrival).map(p=>({id:'arrival-'+p.id,petIds:[p.id],date:p.arrival,precision:p.arrivalPrecision,title:p.name+'来到这个家',description:p.story,type:'arrival',source:p.source}));return [...arrivals,...milestones.filter(m=>m.type!=='arrival'&&m.petIds.some(id=>s.pets.some(p=>p.id===id))),...s.events,...s.photos.map(p=>({id:p.id,petIds:p.petIds,date:p.capturedAt,title:p.title,description:p.description,type:'photo',photo:p,source:p.source})),...s.health.map(h=>({id:h.id,petIds:[h.petId],date:h.date,title:h.type==='weight'?`体重 ${h.value} kg`:`${h.type==='vaccine'?'疫苗':'驱虫'} · ${h.title}`,description:h.note,type:'health',source:h.source})),...s.behaviors.map(h=>({id:h.id,petIds:[h.petId],date:h.date,title:h.category+'观察',description:h.note,type:'behavior',source:h.source})),...s.tasks.filter(t=>t.completedAt).map(t=>({id:t.id,petIds:[t.petId],date:today(t.completedAt),createdAt:t.completedAt,title:'完成照护 · '+t.title,description:'由 '+(s.members.find(m=>m.id===t.assignee)?.name||'我')+' 完成（本机演示操作）',type:'care',source:'ownerReported'}))].sort(sortDated);}
export function growth(s,ui){
 const q=ui.growthSearch.toLocaleLowerCase();const check=p=>matchPet(p,s.selected)&&(!q||[p.title,p.description,...(p.tags||[])].join(' ').toLocaleLowerCase().includes(q))&&(!ui.growthDate||(p.capturedAt||p.date||'').startsWith(ui.growthDate));
 const photos=s.photos.filter(check).sort(sortDated);const events=timelineItems(s).filter(check).filter(p=>ui.eventType==='all'||p.type===ui.eventType);
 return heading('THE DAYS WE KEEP','把日子，慢慢收进相册','按拍摄时间，回到每一个生活片段。',b('上传照片','photo-add',{iconName:'plus'}))+`<div class="growth-toolbar"><div class="segmented" role="group" aria-label="成长视图">${['album','timeline'].map(v=>`<button data-action="growth-mode" data-id="${v}" class="${ui.growthMode===v?'active':''}" aria-pressed="${ui.growthMode===v}">${v==='album'?'家庭相册':'成长时间线'}</button>`).join('')}</div><span class="fine">${ui.growthMode==='album'?photos.length+' 张照片':events.length+' 件小事'}</span></div><form id="growth-search" class="filter-bar"><label class="search-field">${icon('search')}<input name="search" value="${e(ui.growthSearch)}" placeholder="搜索标题、描述或标签" aria-label="搜索照片和时间线"></label><label class="compact-field">月份<input name="month" type="month" value="${e(ui.growthDate)}" aria-label="按月份筛选"></label><button class="btn secondary" type="submit">筛选</button>${b('清除','growth-clear',{kind:'text'})}</form><p class="fine">文字搜索；相册使用拍摄时间，家庭动态使用上传时间。公开案例照片已筛选，新增照片默认只保存在本机。</p>
 ${ui.growthMode==='album'?(photos.length?`<div class="album-grid">${photos.map(p=>photoCard(p,s)).join('')}</div>`:empty('没有找到照片','试着切换宠物或清除筛选，也可以上传新的生活片段。',b('上传照片','photo-add',{kind:'secondary'}))):`<div class="chips" aria-label="事件类别">${[['all','全部'],['photo','照片'],['arrival','来到家里'],['health','健康'],['behavior','观察'],['care','照护'],['daily','日常']].map(([v,l])=>`<button class="chip ${ui.eventType===v?'active':''}" data-action="event-filter" data-id="${v}" aria-pressed="${ui.eventType===v}">${l}</button>`).join('')}</div>${b('记一件小事','event-add',{kind:'secondary',iconName:'note'})}${events.length?`<div class="timeline">${events.map(x=>`<article class="timeline-item"><div class="timeline-date">${dateLabel(x.date)}${/^\d{4}-\d{2}$/.test(x.date||'')?'<small>月份记录</small>':''}</div><span class="timeline-dot"></span><div class="timeline-content">${x.photo?`<button class="timeline-photo" data-action="photo-detail" data-id="${e(x.id)}">${photoImage(x.photo)}</button>`:''}<div class="tags">${tag(petNames(s,x.petIds))}${tag(sourceLabel[x.source]||'主人记录','subtle')}</div><h3>${e(x.title)}</h3><p>${e(x.description||'')}</p>${s.events.some(t=>t.id===x.id)?`<div class="record-actions">${ib('编辑日常','event-edit',x.id,'edit')}${ib('删除日常','event-delete',x.id,'trash')}</div>`:''}</div></article>`).join('')}</div>`:empty('还没有这样的记录','到家里程碑、照片和健康记录会一起组成时间线。')}`}`;
}
export function reminderItems(s){const out=[];for(const p of s.pets){for(const type of ['vaccine','deworm']){const records=s.health.filter(h=>h.petId===p.id&&h.type===type).sort(sortDated);const latest=records[0];if(latest?.next){const days=Math.round((Date.parse(latest.next+'T12:00:00Z')-Date.parse(today()+'T12:00:00Z'))/86400000);out.push({date:latest.next,title:p.name+' · '+(type==='vaccine'?'疫苗':'驱虫'),label:days<0?'计划日期已过，请确认':days===0?'今天的计划':`${days}天后`,petId:p.id});}}}for(const t of s.tasks.filter(t=>!t.completedAt))out.push({date:t.date,title:(s.pets.find(p=>p.id===t.petId)?.name||'宠物')+' · '+t.title,label:'照护计划',petId:t.petId});return out.filter(r=>s.selected==='all'||s.selected===r.petId).sort((a,b)=>a.date.localeCompare(b.date));}
export function taskCard(t,s){return `<article class="task-card ${t.completedAt?'completed':''}"><button class="task-check" data-action="task-toggle" data-id="${e(t.id)}" aria-label="${t.completedAt?'撤销完成':'完成任务'}：${e(t.title)}" aria-pressed="${!!t.completedAt}">${t.completedAt?icon('check'):''}</button><div><h3>${e(t.title)}</h3><p>${e(s.pets.find(p=>p.id===t.petId)?.name)} · ${e(s.members.find(m=>m.id===t.assignee)?.name||'我')}（演示身份）</p><small>${dateLabel(t.date)}${t.completedAt?' · 已完成':''}${t.note?' · '+e(t.note):''}</small></div><div class="record-actions">${ib('编辑照护','task-edit',t.id,'edit')}${ib('删除照护','task-delete',t.id,'trash')}</div></article>`;}
function weightChart(records,unit){
 const rows=[...records].sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt.localeCompare(b.createdAt));if(rows.length<2)return `<p class="chart-empty">${rows.length?'已有1次实测，再记录一次就能看见趋势。':'暂无实测记录。估算体重不会组成历史曲线。'}</p>`;
 const min=Math.min(...rows.map(r=>r.value))*.97,max=Math.max(...rows.map(r=>r.value))*1.03;const range=max-min||1;const start=Date.parse(rows[0].date),end=Date.parse(rows.at(-1).date);const pts=rows.map((r,i)=>({x:end===start?24+i/(rows.length-1)*452:24+(Date.parse(r.date)-start)/(end-start)*452,y:100-(r.value-min)/range*70,r}));return `<svg class="weight-chart" viewBox="0 0 500 130" role="img" aria-label="实测体重趋势，共${rows.length}次。最近${rows.at(-1).value*(unit==='斤'?2:1)}${unit}"><path class="chart-grid" d="M24 30H476M24 65H476M24 100H476"/><polyline points="${pts.map(p=>p.x+','+p.y).join(' ')}"/>${pts.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="3"><title>${p.r.date}：${p.r.value*(unit==='斤'?2:1)} ${unit}</title></circle>`).join('')}<text x="24" y="125">${e(rows[0].date)}</text><text x="476" y="125" text-anchor="end">${e(rows.at(-1).date)}</text></svg>`;
}
export function health(s,ui){
 const pets=s.pets.filter(p=>s.selected==='all'||p.id===s.selected);const reminders=reminderItems(s);const records=s.health.filter(h=>matchPet(h,s.selected)&&(ui.healthType==='all'||h.type===ui.healthType)).sort(sortDated);const behaviors=s.behaviors.filter(h=>matchPet(h,s.selected)).sort(sortDated);const tasks=s.tasks.filter(h=>matchPet(h,s.selected)).sort((a,b)=>!!a.completedAt-!!b.completedAt||a.date.localeCompare(b.date));
 return heading('CARE, WITH A LITTLE ORDER','照顾，也可以从容一点','记录已发生的事，安排下一件小事。',b('添加记录','health-add',{iconName:'plus'}))+`<div class="notice">${icon('lock')}健康记录与新照片只保存在本机。这里不提供诊断，也不会自动推算疫苗或驱虫周期。</div>
 <div class="health-overview">${pets.map(p=>{const weight=s.health.filter(h=>h.petId===p.id&&h.type==='weight').sort(sortDated);const latest=weight[0];return `<section class="health-pet"><div class="health-pet-top">${avatar(p)}<div><h2>${e(p.name)}</h2><p>${e(p.age)} · 估算</p></div>${b('称重','health-weight',{id:p.id,kind:'text',iconName:'plus'})}</div><div class="weight-number">${latest?(latest.value*(s.settings.unit==='斤'?2:1)).toLocaleString('zh-CN',{maximumFractionDigits:2}):p.weightEstimate?`约${p.weightEstimate*(s.settings.unit==='斤'?2:1)}`:'—'}<span>${s.settings.unit}</span></div><p class="fine">${latest?'实测 · '+dateLabel(latest.date):p.weightEstimate?'主人估算 · 测量日期未知':'还没有体重记录'}</p>${weightChart(weight,s.settings.unit)}<div class="health-status">${['vaccine','deworm'].map(type=>{const r=s.health.filter(h=>h.petId===p.id&&h.type===type).sort(sortDated)[0];return `<div><span>${icon(type)}${type==='vaccine'?'疫苗':'驱虫'}</span><strong>${r?dateLabel(r.date):'待记录'}</strong><small>${r?.next?'下次计划 '+dateLabel(r.next):'下次日期未设置'}</small></div>`;}).join('')}</div></section>`;}).join('')}</div><div class="unit-control">显示单位 <div class="segmented">${['kg','斤'].map(x=>`<button data-action="unit" data-id="${x}" aria-pressed="${s.settings.unit===x}" class="${s.settings.unit===x?'active':''}">${x}</button>`).join('')}</div></div>
 <section class="reminder-section"><div class="section-title"><h2>计划与提醒</h2>${b('安排照护','task-add',{kind:'text',iconName:'plus'})}</div>${reminders.length?`<div class="reminders">${reminders.map(r=>`<p>${icon('bell')}<span>${e(r.title)}<small>${dateLabel(r.date)} · ${e(r.label)}</small></span></p>`).join('')}</div>`:empty('还没有计划提醒','填写你确认过的下次日期，或创建一项照护任务。')}</section>
 <div class="section-title"><h2>健康记录</h2><span class="fine">${records.length} 条</span></div><div class="chips">${[['all','全部'],['weight','体重'],['vaccine','疫苗'],['deworm','驱虫']].map(([v,l])=>`<button class="chip ${ui.healthType===v?'active':''}" data-action="health-filter" data-id="${v}" aria-pressed="${ui.healthType===v}">${l}</button>`).join('')}</div>${records.length?`<div class="record-list">${records.map(h=>`<article class="record-card"><span class="record-icon">${icon(h.type)}</span><div><h3>${h.type==='weight'?`体重 · ${h.value} kg / ${h.value*2} 斤`:e(h.title)}</h3><p>${e(petNames(s,[h.petId]))} · ${dateLabel(h.date)}${h.next?' · 下次 '+dateLabel(h.next):''}</p>${h.note?`<p class="record-note">${e(h.note)}</p>`:''}</div><div class="record-actions">${ib('编辑健康记录','health-edit',h.id,'edit')}${ib('删除健康记录','health-delete',h.id,'trash')}</div></article>`).join('')}</div>`:empty('把第一次记录留在这里','真实资料中没有疫苗、驱虫或历史实测体重；不会生成虚构记录。',b('添加记录','health-add',{kind:'secondary'}))}
 <div class="section-title"><h2>生活观察</h2>${b('记下观察','behavior-add',{kind:'text',iconName:'plus'})}</div><div class="owner-observations">${pets.filter(p=>p.diet).map(p=>`<p><strong>${e(p.name)}的吃饭习惯</strong>${e(p.diet)}<small>主人提供 · 观察日期未知</small></p>`).join('')}</div>${behaviors.length?behaviors.map(h=>`<article class="record-card"><span class="record-icon">${icon('note')}</span><div><h3>${e(h.category)}</h3><p>${e(petNames(s,[h.petId]))} · ${dateLabel(h.date)}</p><p class="record-note">${e(h.note)}</p></div><div class="record-actions">${ib('编辑观察','behavior-edit',h.id,'edit')}${ib('删除观察','behavior-delete',h.id,'trash')}</div></article>`).join(''):empty('变化，从观察开始','可以记下食欲、睡眠、排泄、互动或异常情况；不会自动判断健康状况。')}
 <div class="section-title"><h2>共同照护</h2>${b('创建任务','task-add',{kind:'text',iconName:'plus'})}</div>${tasks.length?tasks.map(t=>taskCard(t,s)).join(''):empty('一件小事，一起完成','分配给自己也可以；成员协作是本机演示，不会发送通知。',b('创建任务','task-add',{kind:'secondary'}))}`;
}
export const visiblePosts=s=>s.posts.filter(p=>!s.reported.includes(p.id)&&!s.blocked.includes(p.ownerId));
export function postCard(p,s){return `<article class="post-card">${p.image||p.mediaId?`<button class="post-image" data-action="post-detail" data-id="${e(p.id)}">${photoImage(p)}</button>`:`<div class="small-animal">${icon('growth')}<span>${e(p.species||'宠物')}</span></div>`}<div class="post-body"><div class="post-topline"><span>${e(p.petName||petNames(s,p.petIds)||'宠物')} · ${e(p.city)}</span>${ib('动态选项','post-options',p.id,'more')}</div><h3><button data-action="post-detail" data-id="${e(p.id)}">${e(p.title)}</button></h3><p>${e(p.text)}</p><div class="tags">${tag(p.topic||'养宠日常')}${tag(p.source==='demo'?'演示数据':p.own?'本机分享':'公开案例','subtle')}</div><div class="post-actions"><button data-action="post-like" data-id="${e(p.id)}" class="${s.liked.includes(p.id)?'chosen':''}" aria-label="喜欢${e(p.title)}" aria-pressed="${s.liked.includes(p.id)}">${icon('heart')}<span>${s.liked.includes(p.id)?'已喜欢':'喜欢'}</span></button><button data-action="post-save" data-id="${e(p.id)}" class="${s.saved.includes(p.id)?'chosen':''}" aria-label="收藏${e(p.title)}" aria-pressed="${s.saved.includes(p.id)}">${icon('bookmark')}<span>${s.saved.includes(p.id)?'已收藏':'收藏'}</span></button><button data-action="post-detail" data-id="${e(p.id)}" aria-label="查看动态与本机评论">${icon('chat')}<span>${p.comments?.length||0}</span></button></div></div></article>`;}
export function discover(s,ui){
 let content='';
 if(ui.discoverTab==='bottle'){
 const bottles=visiblePosts(s).filter(p=>p.destination==='bottle'||p.destination==='both'||p.source==='demo'||p.source==='library');const p=bottles.length?bottles[ui.bottleIndex%bottles.length]:null;const pet=s.pets.find(t=>p?.petIds?.includes(t.id));
 content=`<div class="bottle-intro"><p class="eyebrow">A LITTLE HELLO</p><h2>遇见一只，<br>也在好好生活的毛孩子。</h2><p>给宠物留一点善意。不匹配主人，没有私信。</p></div>${p?`<article class="bottle-card"><div class="bottle-photo">${photoImage(p,{large:true})}<span class="bottle-stamp">PET POSTCARD</span></div><div class="bottle-body"><div class="post-topline"><div><h3>${e(p.petName||petNames(s,p.petIds))}</h3><p>${e(p.city)}${pet?' · '+e(pet.age)+'（估算）':' · 年龄待确认'} · ${p.source==='demo'?'演示宠物':p.own?'本机分享':'公开案例'}</p></div>${ib('漂流瓶选项','post-options',p.id,'more')}</div><p class="bottle-note">${e(p.text)}</p><div class="bottle-feedback">${['摸摸头','好可爱'].map(v=>`<button class="btn secondary ${s.bottleFeedback[p.id]===v?'chosen':''}" data-action="bottle-feedback" data-id="${e(p.id)}" data-value="${v}" aria-pressed="${s.bottleFeedback[p.id]===v}">${icon('heart')}${v}${s.bottleFeedback[p.id]===v?' · 已送出':''}</button>`).join('')}</div></div></article><div class="bottle-footer">${b('下一只','bottle-next',{kind:'secondary',iconName:'arrow'})}${b('我也要分享','post-add-bottle',{iconName:'plus'})}</div><p class="fine center">互动只保存在本机。没有在线用户统计或真实消息推送。</p>`:empty('暂时没有漂流瓶','你隐藏了当前内容，或还没有本机分享。可以重置隐藏内容或分享一张照片。',b('分享漂流瓶','post-add-bottle',{kind:'secondary'}))}`;
 }else if(ui.discoverTab==='square'){
 const posts=visiblePosts(s).filter(p=>p.destination!=='bottle').filter(p=>(ui.species==='全部'||p.species===ui.species)&&(!ui.topic||p.topic===ui.topic)&&(!ui.city||p.city===ui.city)&&(!ui.onlySaved||s.saved.includes(p.id)));
 content=`<div class="section-title"><h2>分享的，是宠物的生活</h2>${b('发一条动态','post-add',{iconName:'plus'})}</div><form id="square-filter" class="filter-bar"><label>宠物<select name="species">${['全部','猫咪','狗狗','其他宠物'].map(x=>`<option ${ui.species===x?'selected':''}>${x}</option>`).join('')}</select></label><label>话题<select name="topic"><option value="">全部话题</option>${topics.map(x=>`<option ${ui.topic===x?'selected':''}>${x}</option>`).join('')}</select></label><label>城市<select name="city"><option value="">所有城市</option>${[...new Set([...s.posts.map(p=>p.city),s.family.city])].map(x=>`<option ${ui.city===x?'selected':''}>${e(x)}</option>`).join('')}</select></label><button class="btn secondary">筛选</button>${b(ui.onlySaved?'查看全部':'我的收藏','saved-filter',{kind:'text'})}</form><p class="fine">公开案例与演示内容用于体验；你发布的动态、点赞、收藏和评论只保存在本机。</p>${posts.length?`<div class="feed-grid">${posts.map(p=>postCard(p,s)).join('')}</div>`:empty('这里暂时没有动态','换个筛选条件，或分享你的宠物日常。',b('发布动态','post-add',{kind:'secondary'}))}`;
 }else{
 const resources=localContents.filter(p=>(!ui.localCity||p.city===ui.localCity)&&(!ui.localDistrict||p.district===ui.localDistrict)&&(ui.localSpecies==='全部'||p.species==='全部'||p.species===ui.localSpecies)&&(!ui.localType||p.type===ui.localType));
 content=`<div class="local-intro">${icon('pin')}<div><h2>从附近的小事开始</h2><p>发现地点、路线、养宠经验与活动。所有地点和活动为演示，未经现实核实。</p></div></div><form id="local-filter" class="filter-bar"><label>城市<select name="city"><option value="">所有城市</option>${['深圳','广州'].map(x=>`<option ${ui.localCity===x?'selected':''}>${x}</option>`).join('')}</select></label><label>区域<select name="district"><option value="">所有区域</option>${[...new Set(localContents.filter(r=>!ui.localCity||r.city===ui.localCity).map(r=>r.district))].map(x=>`<option ${ui.localDistrict===x?'selected':''}>${x}</option>`).join('')}</select></label><label>宠物<select name="species">${['全部','猫咪','狗狗','其他宠物'].map(x=>`<option ${ui.localSpecies===x?'selected':''}>${x}</option>`).join('')}</select></label><label>内容<select name="type"><option value="">所有类型</option>${[...new Set(localContents.map(p=>p.type))].map(x=>`<option ${ui.localType===x?'selected':''}>${x}</option>`).join('')}</select></label><button class="btn secondary">筛选</button>${b('重置','local-clear',{kind:'text'})}</form>${resources.length?`<div class="resource-grid">${resources.map(r=>`<article class="resource-card"><div class="resource-visual">${icon(r.type==='散步路线'?'discover':r.type==='本地照护经验'?'note':'pin')}<span>${e(r.type)}</span></div><div class="resource-body"><div class="tags">${tag('演示 · 未核实','warm')}${tag(r.city+' · '+r.district,'subtle')}</div><h3>${e(r.title)}</h3><p>${e(r.text)}</p><div class="resource-actions">${b('查看内容','resource-detail',{id:r.id,kind:'text',iconName:'arrow'})}${ib(s.resourceSaved.includes(r.id)?'取消收藏资源':'收藏资源','resource-save',r.id,'bookmark')}</div></div></article>`).join('')}</div>`:empty('暂时没有这类本地内容','可以切换区域或重置筛选。',b('重置筛选','local-clear',{kind:'secondary'}))}`;
 }
 return heading('LITTLE LIVES, BIG WORLD','看看别家的好日子','分享一点日常，发现一点新的养宠生活。')+`<div class="discovery-tabs" role="group" aria-label="发现栏目">${[['bottle','bottle','宠物漂流瓶'],['square','people','宠友广场'],['local','pin','同城探索']].map(([id,ic,l])=>`<button class="${ui.discoverTab===id?'active':''}" data-action="discover-tab" data-id="${id}" aria-pressed="${ui.discoverTab===id}">${icon(ic)}<span>${l}</span></button>`).join('')}</div>${content}`;
}
