import {esc as e,icon,button as b,iconButton as ib,tag,empty,dateLabel,timeLabel,matchPet,sortDated,sourceLabel,today} from './utils.js?v=3.2.0';
import {milestones,localContents,topics} from './data.js?v=3.2.0';
import {metricsStrip,currentWeight,chart,metricNames,metricUnits,trendNotice,eventRows,eventList,deviceDefinitions,shiftDay} from './devices.js?v=3.2.0';
export const petNames=(s,ids)=>(ids||[]).map(id=>s.pets.find(p=>p.id===id)?.name||'未知宠物').join('、');
export function photoImage(p,{large=false,alt='',eager=false}={}){
 const url=large?(p.large||p.image||p.src):(p.image||p.src||p.thumb);
 return url?`<img src="${e(url)}" ${p.thumb&&p.large?`srcset="${e(p.thumb)} 400w, ${e(p.image)} 1000w, ${e(p.large)} 1600w" sizes="(max-width: 600px) 48vw, 500px"`:''} alt="${e(alt||p.title||'宠物照片')}" loading="${eager?'eager':'lazy'}" decoding="async" ${p.width&&p.height?`width="${p.width}" height="${p.height}"`:''}>`:p.mediaId?`<img data-media="${e(p.mediaId)}" alt="${e(alt||p.title||'上传的宠物照片')}" loading="lazy">`:`<div class="image-placeholder">${icon('growth')}<span>还没有照片</span></div>`;
}
export const avatar=p=>p.cover||p.coverMediaId?`<img class="pet-avatar" ${p.cover?`src="${e(p.cover)}"`:`data-media="${e(p.coverMediaId)}"`} alt="${e(p.name)}">`:`<span class="pet-avatar initials">${e(p.name.slice(0,1))}</span>`;
export const heading=(kicker,title,text,action='')=>`<div class="page-heading"><div><p class="eyebrow">${e(kicker)}</p><h1>${e(title)}</h1>${text?`<p class="lead">${e(text)}</p>`:''}</div>${action}</div>`;
export function home(s){
 const pets=s.pets.filter(p=>s.selected==='all'||p.id===s.selected),photos=s.photos.filter(p=>matchPet(p,s.selected)).sort(sortDated),tasks=s.tasks.filter(t=>!t.completedAt&&matchPet(t,s.selected)).sort((a,b)=>a.date.localeCompare(b.date)),reminders=reminderItems(s).filter(r=>r.kind==='health').slice(0,3),recent=photos.slice(0,4),newPhotos=s.photos.filter(p=>matchPet(p,s.selected)&&p.source!=='library'&&today(p.uploadedAt)===today()),daily=s.events.filter(x=>matchPet(x,s.selected)&&x.date===today());
 return heading(today().replaceAll('-',' / '),'家里的今天','',b('记录','record-menu',{iconName:'plus'}))+(!pets.length?empty('欢迎来到你的空间','先给伙伴建个档案，再把一起生活的日子留在这里。',b('添加宠物','pet-add',{kind:'secondary'})):
 '<div class="pet-grid home-portraits">'+pets.map(p=>'<article class="pet-card"><button class="pet-photo" data-action="pet-detail" data-id="'+e(p.id)+'" aria-label="查看'+e(p.name)+'档案">'+photoImage({image:p.cover,mediaId:p.coverMediaId,title:p.name},{eager:true})+'<span class="photo-label">'+e(p.name)+' '+icon('arrow')+'</span></button><div class="portrait-caption">'+e(p.bio||p.breed)+'</div></article>').join('')+'</div>')+
 '<div class="home-actions">'+b('上传照片','photo-add',{iconName:'growth'})+b('记一件小事','event-add',{kind:'secondary',iconName:'note'})+b('添加伙伴','pet-add',{kind:'text',iconName:'plus'})+'</div>'+
 '<section class="today-section"><div class="section-title"><h2>今天的小事</h2><span class="fine">'+(tasks.length?'还有 '+tasks.length+' 件待办':'')+'</span></div>'+(tasks.length?tasks.slice(0,3).map(t=>taskCard(t,s)).join(''):'<p class="quiet-empty">今天的照护都安排好了。'+b('安排一件小事','task-add',{kind:'text'})+'</p>')+newPhotos.map(p=>'<button class="today-entry" data-action="photo-detail" data-id="'+e(p.id)+'">'+photoImage(p)+'<span>新照片 · '+e(p.title)+'<small>'+timeLabel(p.uploadedAt)+'</small></span>'+icon('arrow')+'</button>').join('')+daily.map(x=>'<button class="today-entry" data-action="event-edit" data-id="'+e(x.id)+'">'+icon('note')+'<span>'+e(x.title)+'<small>'+e(petNames(s,x.petIds))+'</small></span>'+icon('arrow')+'</button>').join('')+'</section>'+
 (pets.length?'<section class="home-health"><div class="section-title"><h2>今天，状态怎么样</h2>'+b('查看健康','go-health',{kind:'text',iconName:'arrow'})+'</div>'+pets.map(p=>'<div class="home-health-row"><button class="mini-pet" data-action="health-open" data-id="'+p.id+':food">'+avatar(p)+'<strong>'+e(p.name)+'</strong></button>'+metricsStrip(s,p)+'</div>').join('')+'</section>':'')+
 (reminders.length?'<section><div class="section-title"><h2>近期提醒</h2>'+b('查看计划','go-health',{kind:'text',iconName:'arrow'})+'</div><div class="reminders">'+reminders.map(r=>'<button class="reminder-link" data-action="health-open" data-id="'+r.petId+':weight">'+icon('bell')+'<span>'+e(r.title)+'<small>'+dateLabel(r.date)+' · '+e(r.label)+'</small></span>'+icon('arrow')+'</button>').join('')+'</div></section>':'')+
 '<div class="section-title"><h2>最近的照片</h2>'+b('全部照片','go-growth',{kind:'text',iconName:'arrow'})+'</div>'+(recent.length?'<div class="recent-grid recent-life">'+recent.map(p=>photoCard(p,s)).join('')+'</div>':empty('还没有照片','下一次可爱的瞬间，记得留下来。',b('上传照片','photo-add',{kind:'secondary'})))+
 (s.activity.length?'<details class="activity-history"><summary>最近的记录</summary><div class="activity-list">'+s.activity.slice(0,5).map(a=>'<div><span class="activity-dot"></span><p>'+e(a.text)+'<small>'+timeLabel(a.createdAt)+'</small></p></div>').join('')+'</div></details>':'');
}
export function petDetail(p,s){const measured=s?.health.filter(h=>h.petId===p.id&&h.type==='weight').sort(sortDated)[0];return `<div class="pet-detail-cover">${p.cover||p.coverMediaId?photoImage({image:p.cover,mediaId:p.coverMediaId,title:p.name},{large:true}):photoImage({})}</div><div class="tags">${tag(p.sex)}${tag(p.age+' · '+(p.ageSource==='estimated'?'估算':'主人填写'))}${tag(p.fur||'毛发待确认')}</div><p class="detail-bio">${e(p.bio)}</p><dl class="detail-list"><div><dt>品种</dt><dd>${e(p.breed)}</dd></div><div><dt>来到家里</dt><dd>${dateLabel(p.arrival)}${p.arrivalPrecision==='month'?' · 仅知月份':''}</dd></div><div><dt>当前体重</dt><dd>${measured?`${measured.value} kg / ${measured.value*2} 斤 · 实测，${dateLabel(measured.date)}`:p.weightEstimate?`约 ${p.weightEstimate} kg / ${p.weightEstimate*2} 斤 · 主人估算，测量日期未知`:'待记录'}</dd></div><div><dt>绝育状态</dt><dd>${e(p.spay||'待确认')}</dd></div></dl><div class="detail-sections">${[['相遇的故事',p.story],['身体特点',p.body],['吃饭习惯',p.diet],['相处与边界',p.boundary],['家里的日常',p.interaction]].map(([h,t])=>`<section><h3>${e(h)}</h3><p>${e(t||'待补充')}</p></section>`).join('')}</div>${p.id==='erduo'?`<p class="notice">主人对血统有猜测，但未经证实，不作为品种信息。发现时有耳螨；治疗及恢复信息待确认。</p>`:''}${b('编辑档案','pet-edit',{id:p.id,kind:'secondary',iconName:'edit'})}`;}
export function photoCard(p,s){return `<article class="photo-card"><button data-action="photo-detail" data-id="${e(p.id)}" class="photo-open" aria-label="查看照片：${e(p.title)}">${photoImage(p)}<span class="photo-card-meta"><strong>${e(p.title)}</strong><span>${e(petNames(s,p.petIds))} · ${dateLabel(p.capturedAt)}</span></span></button>${p.source==='library'?'':'<span class="privacy-label">'+icon('lock')+'私密</span>'}</article>`;}
export function timelineItems(s){const arrivals=s.pets.filter(p=>p.arrival).map(p=>({id:'arrival-'+p.id,petIds:[p.id],date:p.arrival,precision:p.arrivalPrecision,title:p.name+'来到这个家',description:p.story,type:'arrival',source:p.source}));return [...arrivals,...milestones.filter(m=>m.type!=='arrival'&&m.petIds.some(id=>s.pets.some(p=>p.id===id))),...s.events,...s.photos.map(p=>({id:p.id,petIds:p.petIds,date:p.capturedAt,title:p.title,description:p.description,type:'photo',photo:p,source:p.source})),...s.health.map(h=>({id:h.id,petIds:[h.petId],date:h.date,title:h.type==='weight'?`体重 ${h.value} kg`:`${h.type==='vaccine'?'疫苗':'驱虫'} · ${h.title}`,description:h.note,type:'health',source:h.source})),...s.behaviors.map(h=>({id:h.id,petIds:[h.petId],date:h.date,title:h.category+'观察',description:h.note,type:'behavior',source:h.source})),...s.tasks.filter(t=>t.completedAt).map(t=>({id:t.id,petIds:[t.petId],date:today(t.completedAt),createdAt:t.completedAt,title:'完成照护 · '+t.title,description:'由 '+(s.members.find(m=>m.id===t.assignee)?.name||'我')+' 完成',type:'care',source:'ownerReported'}))].sort(sortDated);}
export function albumPhotos(s,ui){const q=ui.growthSearch.toLocaleLowerCase();return s.photos.filter(p=>matchPet(p,s.selected)&&(!q||[p.title,p.description,...(p.tags||[])].join(' ').toLocaleLowerCase().includes(q))&&(!ui.growthDate||(p.capturedAt||'').startsWith(ui.growthDate))&&(!ui.growthYear||(p.capturedAt||'').startsWith(ui.growthYear))&&(!ui.growthThen||ui.growthThen==='month'&&p.capturedAt&&p.capturedAt.slice(5,7)===today().slice(5,7)&&p.capturedAt.slice(0,4)<today().slice(0,4)||ui.growthThen==='early'&&p.petIds.some(id=>{const pet=s.pets.find(x=>x.id===id);return pet?.arrival&&p.capturedAt&&p.capturedAt.slice(0,7)>=pet.arrival&&p.capturedAt.slice(0,10)<=shiftDay(pet.arrival+'-01',183);}))).sort(sortDated);}
export function growth(s,ui){
 const photos=albumPhotos(s,ui),years=[...new Set(s.photos.filter(p=>matchPet(p,s.selected)&&p.capturedAt).map(p=>p.capturedAt.slice(0,4)))].sort().reverse(),q=ui.growthSearch.toLowerCase(),events=timelineItems(s).filter(p=>matchPet(p,s.selected)&&(!ui.growthYear||(p.date||'').startsWith(ui.growthYear))&&(!ui.growthDate||(p.date||'').startsWith(ui.growthDate))&&(!q||[p.title,p.description].join(' ').toLowerCase().includes(q))&&(ui.eventType==='all'||p.type===ui.eventType)),groups=new Map();for(const p of photos){const month=p.capturedAt?p.capturedAt.slice(0,7):'';if(!groups.has(month))groups.set(month,[]);groups.get(month).push(p);}
 return heading('OUR ALBUM','生活相册','',b('上传照片','photo-add',{iconName:'plus'}))+'<div class="growth-toolbar"><div class="segmented" aria-label="成长视图">'+['album','timeline'].map(v=>'<button data-action="growth-mode" data-id="'+v+'" class="'+(ui.growthMode===v?'active':'')+'" aria-pressed="'+(ui.growthMode===v)+'">'+(v==='album'?'照片':'时间线')+'</button>').join('')+'</div><span class="fine">'+(ui.growthMode==='album'?photos.length+' 张':events.length+' 件')+'</span></div>'+
 '<form id="growth-search" class="filter-bar album-search"><label class="search-field">'+icon('search')+'<input name="search" value="'+e(ui.growthSearch)+'" placeholder="搜索描述、标签或标题" aria-label="搜索照片"></label><label>年份<select name="year" aria-label="照片年份"><option value="">所有年份</option>'+years.map(y=>'<option '+(y===ui.growthYear?'selected':'')+'>'+y+'</option>').join('')+'</select></label><label class="compact-field">月份<input name="month" type="month" value="'+e(ui.growthDate)+'" aria-label="按月份筛选"></label><button class="btn secondary">查找</button>'+b('清除','growth-clear',{kind:'text'})+'</form>'+
 (ui.growthMode==='album'?'<div class="then-row"><span>那时候的我们</span><div class="chips">'+[['','全部时光'],['month','往年同月'],['early','初到家时']].map(([v,l])=>'<button data-action="growth-then" data-id="'+v+'" class="chip '+(ui.growthThen===v?'active':'')+'" aria-pressed="'+(ui.growthThen===v)+'">'+l+'</button>').join('')+'</div></div>'+(!ui.growthSearch&&!ui.growthYear&&!ui.growthDate&&!ui.growthThen?'<div class="arrival-stories">'+s.pets.filter(p=>matchPet(p,s.selected)&&p.arrival).map(p=>'<button data-action="arrival-view" data-id="'+p.id+'"><span>'+dateLabel(p.arrival)+'</span><strong>'+e(p.name)+'来到这个家</strong><small>'+e(p.story||'我们的故事从这里开始。')+'</small>'+icon('arrow')+'</button>').join('')+'</div>':'')+(photos.length?[...groups].map(([month,ps])=>'<section class="album-month"><div class="month-heading"><h2>'+(month?month.replace('-','年')+'月':'拍摄日期待补充')+'</h2><span>'+ps.length+' 张</span></div><div class="album-grid">'+ps.map(p=>photoCard(p,s)).join('')+'</div></section>').join(''):empty(ui.growthThen?'这段时光还没有照片':'没有找到照片','试试其他年份、月份或关键词。',b('清除筛选','growth-clear',{kind:'secondary'}))):
 '<div class="chips">'+[['all','全部'],['photo','照片'],['arrival','来到家里'],['health','健康'],['behavior','观察'],['care','照护'],['daily','日常']].map(([v,l])=>'<button class="chip '+(ui.eventType===v?'active':'')+'" data-action="event-filter" data-id="'+v+'">'+l+'</button>').join('')+'</div>'+b('记一件小事','event-add',{kind:'secondary',iconName:'note'})+(events.length?'<div class="timeline">'+events.map(x=>'<article class="timeline-item"><div class="timeline-date">'+dateLabel(x.date)+'</div><span class="timeline-dot"></span><div class="timeline-content">'+(x.photo?'<button class="timeline-photo" data-action="photo-detail" data-id="'+e(x.id)+'">'+photoImage(x.photo)+'</button>':'')+'<div class="tags">'+tag(petNames(s,x.petIds))+'</div><h3>'+e(x.title)+'</h3><p>'+e(x.description||'')+'</p>'+(s.events.some(t=>t.id===x.id)?'<div class="record-actions">'+ib('编辑日常','event-edit',x.id,'edit')+ib('删除日常','event-delete',x.id,'trash')+'</div>':'')+'</div></article>').join('')+'</div>':empty('还没有这样的记录','照片、健康与照护会一起组成时间线。')));
}
export function reminderItems(s){const out=[];for(const p of s.pets){for(const type of ['vaccine','deworm']){const records=s.health.filter(h=>h.petId===p.id&&h.type===type).sort(sortDated);const latest=records[0];if(latest?.next){const days=Math.round((Date.parse(latest.next+'T12:00:00Z')-Date.parse(today()+'T12:00:00Z'))/86400000);out.push({date:latest.next,title:p.name+' · '+(type==='vaccine'?'疫苗':'驱虫'),label:days<0?'计划日期已过，请确认':days===0?'今天的计划':`${days}天后`,petId:p.id,kind:'health'});}}}for(const t of s.tasks.filter(t=>!t.completedAt))out.push({date:t.date,title:(s.pets.find(p=>p.id===t.petId)?.name||'宠物')+' · '+t.title,label:'照护计划',petId:t.petId,kind:'task'});return out.filter(r=>s.selected==='all'||s.selected===r.petId).sort((a,b)=>a.date.localeCompare(b.date));}
export function taskCard(t,s){return `<article class="task-card ${t.completedAt?'completed':''}"><button class="task-check" data-action="task-toggle" data-id="${e(t.id)}" aria-label="${t.completedAt?'撤销完成':'完成任务'}：${e(t.title)}" aria-pressed="${!!t.completedAt}">${t.completedAt?icon('check'):''}</button><div><h3>${e(t.title)}</h3><p>${e(s.pets.find(p=>p.id===t.petId)?.name)} · ${e(s.members.find(m=>m.id===t.assignee)?.name||'我')}</p><small>${dateLabel(t.date)}${t.completedAt?' · 已完成':''}${t.note?' · '+e(t.note):''}</small></div><div class="record-actions">${ib('编辑照护','task-edit',t.id,'edit')}${ib('删除照护','task-delete',t.id,'trash')}</div></article>`;}
function weightChart(records,unit){
 const rows=[...records].sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt.localeCompare(b.createdAt));if(rows.length<2)return `<p class="chart-empty">${rows.length?'已有1次实测，再记录一次就能看见趋势。':'暂无实测记录。估算体重不会组成历史曲线。'}</p>`;
 const min=Math.min(...rows.map(r=>r.value))*.97,max=Math.max(...rows.map(r=>r.value))*1.03;const range=max-min||1;const start=Date.parse(rows[0].date),end=Date.parse(rows.at(-1).date);const pts=rows.map((r,i)=>({x:end===start?24+i/(rows.length-1)*452:24+(Date.parse(r.date)-start)/(end-start)*452,y:100-(r.value-min)/range*70,r}));return `<svg class="weight-chart" viewBox="0 0 500 130" role="img" aria-label="实测体重趋势，共${rows.length}次。最近${rows.at(-1).value*(unit==='斤'?2:1)}${unit}"><path class="chart-grid" d="M24 30H476M24 65H476M24 100H476"/><polyline points="${pts.map(p=>p.x+','+p.y).join(' ')}"/>${pts.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="3"><title>${p.r.date}：${p.r.value*(unit==='斤'?2:1)} ${unit}</title></circle>`).join('')}<text x="24" y="125">${e(rows[0].date)}</text><text x="476" y="125" text-anchor="end">${e(rows.at(-1).date)}</text></svg>`;
}
export function health(state,ui){
 const p=state.pets.find(p=>p.id===state.selected)||state.pets.find(p=>p.id==='erduo')||state.pets[0];if(!p)return heading('HEALTH','健康','')+empty('先认识你的伙伴','建档后，就能开始健康记录。',b('添加宠物','pet-add',{kind:'secondary'}));const s={...state,selected:p.id},pets=[p],reminders=reminderItems(s),records=s.health.filter(h=>matchPet(h,s.selected)&&(ui.healthType==='all'||h.type===ui.healthType)).sort(sortDated),behaviors=s.behaviors.filter(h=>matchPet(h,s.selected)).sort(sortDated),tasks=s.tasks.filter(h=>matchPet(h,s.selected)).sort((a,b)=>!!a.completedAt-!!b.completedAt||a.date.localeCompare(b.date)),insight=trendNotice(s,p.id),metric=ui.healthMetric||'food',days=ui.healthRange||7,events=eventRows(s,p.id,ui.deviceFilter||'all',ui.eventDate||''),deviceMode=s.space==='experience'&&s.devices?.length;
 return heading('HEALTH','健康','',b('添加记录','health-add',{iconName:'plus'}))+
 '<section class="health-pet health-current"><div class="health-pet-top">'+avatar(p)+'<div><h2>'+e(p.name)+'</h2><p>'+e(p.age)+'</p></div>'+b('称重','health-weight',{id:p.id,kind:'text',iconName:'plus'})+'</div>'+metricsStrip(s,p,'metric-open')+'</section>'+
 '<section class="trend-panel"><div class="section-title"><h2>看见变化</h2><div class="segmented" aria-label="趋势范围">'+[7,30,90].map(n=>'<button data-action="health-range" data-id="'+n+'" class="'+(n===days?'active':'')+'" aria-pressed="'+(n===days)+'">'+n+'天</button>').join('')+'</div></div><div class="metric-tabs" aria-label="趋势指标">'+Object.entries(metricNames).map(([id,l])=>'<button data-action="health-metric" data-id="'+id+'" class="'+(metric===id?'active':'')+'" aria-pressed="'+(metric===id)+'">'+l+'<small>'+metricUnits[id]+'</small></button>').join('')+'</div><div class="chart-caption"><span>最近 '+days+' 天 · '+metricNames[metric]+'</span><span>'+ (metric==='weight'?(deviceMode?'设备模拟 / 手动测量':'手动测量'):deviceMode?'设备模拟':'设备未连接')+'</span></div>'+chart(s,p.id,metric,days,ui.chartDate)+'</section>'+
 (insight?'<button class="insight-banner" data-action="related-observation" data-id="'+p.id+'">'+icon('note')+'<span><strong>近7个完整日的平均进食量下降 '+insight.percent+'%</strong><small>看看同期饮水、如厕与观察记录</small></span>'+icon('arrow')+'</button>':'')+
 '<section class="devices-section"><div class="section-title"><h2>家里的设备</h2>'+b('数据来源','mode-info',{kind:'text'})+'</div><div class="device-strip">'+deviceDefinitions.map(d=>'<button data-action="device-detail" data-id="'+d.id+'">'+icon(d.icon)+'<span><strong>'+d.name+'</strong><small><i class="status-dot '+(deviceMode?'connected':'')+'"></i>'+(deviceMode?'已连接 · 模拟':'未连接')+'</small></span>'+icon('arrow')+'</button>').join('')+'</div></section>'+
 '<section class="events-section"><div class="section-title"><h2>发生了什么</h2><span class="fine">'+events.length+' 条</span></div><div class="chips">'+[['all','全部事件'],['food','进食'],['water','饮水'],['toilet','如厕']].map(([v,l])=>'<button class="chip '+(ui.deviceFilter===v?'active':'')+'" data-action="device-filter" data-id="'+v+'">'+l+'</button>').join('')+'</div><label class="event-date">日期<input type="date" id="event-date" value="'+e(ui.eventDate||'')+'" max="'+today()+'"></label>'+(ui.eventDate?b('所有日期','event-date-clear',{kind:'text'}):'')+(events.length?eventList(events,ui.eventLimit||6)+(events.length>(ui.eventLimit||6)?b('再看一些','events-more',{kind:'text',iconName:'plus'}):''): '<p class="quiet-empty">'+(deviceMode?'这一天没有对应事件。':'连接设备后，事件会出现在这里。你也可以先手动记录健康与观察。')+'</p>')+'</section>'+
 '<section class="care-plan"><div class="section-title"><h2>计划与提醒</h2>'+b('安排照护','task-add',{kind:'text',iconName:'plus'})+'</div>'+(reminders.length?'<div class="reminders">'+reminders.map(r=>'<button class="reminder-link" data-action="'+(r.kind==='task'?'task-edit':'health-plan')+'" data-id="'+(r.kind==='task'?s.tasks.find(t=>r.title.endsWith(t.title))?.id:p.id)+'">'+icon('bell')+'<span>'+e(r.title)+'<small>'+dateLabel(r.date)+' · '+e(r.label)+'</small></span>'+icon('arrow')+'</button>').join('')+'</div>':'<p class="quiet-empty">还没有下一次计划。记录疫苗或驱虫时，可以一起记下日期。</p>')+'</section>'+manualHealth(s,ui,p);
}

function manualHealth(s,ui,p){const records=s.health.filter(h=>h.petId===p.id&&(ui.healthType==='all'||h.type===ui.healthType)).sort(sortDated),behaviors=s.behaviors.filter(h=>h.petId===p.id).sort(sortDated),tasks=s.tasks.filter(t=>t.petId===p.id).sort((a,b)=>!!a.completedAt-!!b.completedAt||a.date.localeCompare(b.date));return `<section class="manual-health"><div class="section-title"><h2>健康记录</h2><span class="fine">${records.length} 条</span></div><div class="chips">${[['all','全部'],['weight','体重'],['vaccine','疫苗'],['deworm','驱虫']].map(([v,l])=>'<button class="chip '+(ui.healthType===v?'active':'')+'" data-action="health-filter" data-id="'+v+'">'+l+'</button>').join('')}</div>${records.length?'<div class="record-list">'+records.map(h=>'<article class="record-card"><span class="record-icon">'+icon(h.type)+'</span><div><h3>'+(h.type==='weight'?'体重 · '+h.value+' kg / '+h.value*2+' 斤':e(h.title))+'</h3><p>'+dateLabel(h.date)+(h.next?' · 下次 '+dateLabel(h.next):'')+'</p>'+(h.note?'<p class="record-note">'+e(h.note)+'</p>':'')+'</div><div class="record-actions">'+ib('编辑健康记录','health-edit',h.id,'edit')+ib('删除健康记录','health-delete',h.id,'trash')+'</div></article>').join('')+'</div>':empty('从第一条记录开始','记录称重，或补充疫苗与驱虫日期。',b('添加记录','health-add',{kind:'secondary'}))}<div class="unit-control">体重显示<div class="segmented">${['kg','斤'].map(x=>'<button data-action="unit" data-id="'+x+'" class="'+(s.settings.unit===x?'active':'')+'">'+x+'</button>').join('')}</div></div></section><section><div class="section-title"><h2>生活观察</h2>${b('记下观察','behavior-add',{kind:'text',iconName:'plus'})}</div>${p.diet?'<p class="diet-note"><strong>'+e(p.name)+'的吃饭习惯</strong>'+e(p.diet)+'</p>':''}${behaviors.length?behaviors.map(h=>'<article class="record-card"><span class="record-icon">'+icon('note')+'</span><div><h3>'+e(h.category)+'</h3><p>'+dateLabel(h.date)+'</p><p class="record-note">'+e(h.note)+'</p></div><div class="record-actions">'+ib('编辑观察','behavior-edit',h.id,'edit')+ib('删除观察','behavior-delete',h.id,'trash')+'</div></article>').join(''):'<p class="quiet-empty">留意到新的变化时，记下来。</p>'}</section><section><div class="section-title"><h2>照护事项</h2>${b('创建任务','task-add',{kind:'text',iconName:'plus'})}</div>${tasks.length?tasks.map(t=>taskCard(t,s)).join(''):'<p class="quiet-empty">暂时没有照护事项。</p>'}</section>`;}

export const visiblePosts=s=>s.posts.filter(p=>!s.reported.includes(p.id)&&!s.blocked.includes(p.ownerId));
export function postCard(p,s){return `<article class="post-card">${p.image||p.mediaId?`<button class="post-image" data-action="post-detail" data-id="${e(p.id)}">${photoImage(p)}</button>`:`<div class="small-animal">${icon('growth')}<span>${e(p.species||'宠物')}</span></div>`}<div class="post-body"><div class="post-topline"><span>${e(p.petName||petNames(s,p.petIds)||'宠物')} · ${e(p.city)}</span>${ib('动态选项','post-options',p.id,'more')}</div><h3><button data-action="post-detail" data-id="${e(p.id)}">${e(p.title)}</button></h3><p>${e(p.text)}</p><div class="tags">${tag(p.topic||'养宠日常')}${tag(p.own?'体验分享':'体验内容','subtle')}</div><div class="post-actions"><button data-action="post-like" data-id="${e(p.id)}" class="${s.liked.includes(p.id)?'chosen':''}" aria-label="喜欢${e(p.title)}" aria-pressed="${s.liked.includes(p.id)}">${icon('heart')}<span>${s.liked.includes(p.id)?'已喜欢':'喜欢'}</span></button><button data-action="post-save" data-id="${e(p.id)}" class="${s.saved.includes(p.id)?'chosen':''}" aria-label="收藏${e(p.title)}" aria-pressed="${s.saved.includes(p.id)}">${icon('bookmark')}<span>${s.saved.includes(p.id)?'已收藏':'收藏'}</span></button><button data-action="post-detail" data-id="${e(p.id)}" aria-label="查看动态与评论">${icon('chat')}<span>${p.comments?.length||0}</span></button></div></div></article>`;}
export function discover(s,ui){
 let content='';
 if(ui.discoverTab==='bottle'){
 const bottles=visiblePosts(s).filter(p=>p.destination==='bottle'||p.destination==='both'||p.source==='demo'||p.source==='library');const p=bottles.length?bottles[ui.bottleIndex%bottles.length]:null;const pet=s.pets.find(t=>p?.petIds?.includes(t.id));
 content=`<div class="bottle-intro"><p class="eyebrow">A LITTLE HELLO</p><h2>今天，会遇见谁？</h2><p></p></div>${p?`<article class="bottle-card"><div class="bottle-photo">${photoImage(p,{large:true})}<span class="bottle-stamp">PET POSTCARD</span></div><div class="bottle-body"><div class="post-topline"><div><h3>${e(p.petName||petNames(s,p.petIds))}</h3><p>${e(p.city)}${pet?' · '+e(pet.age)+'（估算）':' · 年龄待确认'} · ${p.own?'体验分享':'体验内容'}</p></div>${ib('漂流瓶选项','post-options',p.id,'more')}</div><p class="bottle-note">${e(p.text)}</p><div class="bottle-feedback">${['摸摸头','好可爱'].map(v=>`<button class="btn secondary ${s.bottleFeedback[p.id]===v?'chosen':''}" data-action="bottle-feedback" data-id="${e(p.id)}" data-value="${v}" aria-pressed="${s.bottleFeedback[p.id]===v}">${icon('heart')}${v}${s.bottleFeedback[p.id]===v?' · 已送出':''}</button>`).join('')}</div></div></article><div class="bottle-footer">${b('下一只','bottle-next',{kind:'secondary',iconName:'arrow'})}${b('我也要分享','post-add-bottle',{iconName:'plus'})}</div>`:empty('暂时没有漂流瓶','你隐藏了当前内容，或还没有本机分享。可以重置隐藏内容或分享一张照片。',b('分享漂流瓶','post-add-bottle',{kind:'secondary'}))}`;
 }else if(ui.discoverTab==='square'){
 const posts=visiblePosts(s).filter(p=>p.destination!=='bottle').filter(p=>(ui.species==='全部'||p.species===ui.species)&&(!ui.topic||p.topic===ui.topic)&&(!ui.city||p.city===ui.city)&&(!ui.onlySaved||s.saved.includes(p.id)));
 content=`<div class="section-title"><h2>宠友的新鲜事</h2>${b('发一条动态','post-add',{iconName:'plus'})}</div><details class="filter-disclosure"><summary>筛选内容${ui.species!=='全部'||ui.topic||ui.city||ui.onlySaved?' · 已筛选':''}</summary><form id="square-filter" class="filter-bar"><label>宠物<select name="species">${['全部','猫咪','狗狗','其他宠物'].map(x=>`<option ${ui.species===x?'selected':''}>${x}</option>`).join('')}</select></label><label>话题<select name="topic"><option value="">全部话题</option>${topics.map(x=>`<option ${ui.topic===x?'selected':''}>${x}</option>`).join('')}</select></label><label>城市<select name="city"><option value="">所有城市</option>${[...new Set([...s.posts.map(p=>p.city),s.family.city])].map(x=>`<option ${ui.city===x?'selected':''}>${e(x)}</option>`).join('')}</select></label><button class="btn secondary">筛选</button>${b(ui.onlySaved?'查看全部':'我的收藏','saved-filter',{kind:'text'})}</form></details>${posts.length?`<div class="feed-grid">${posts.map(p=>postCard(p,s)).join('')}</div>`:empty('这里暂时没有动态','换个筛选条件，或分享你的宠物日常。',b('发布动态','post-add',{kind:'secondary'}))}`;
 }else{
 const resources=localContents.filter(p=>(!ui.localCity||p.city===ui.localCity)&&(!ui.localDistrict||p.district===ui.localDistrict)&&(ui.localSpecies==='全部'||p.species==='全部'||p.species===ui.localSpecies)&&(!ui.localType||p.type===ui.localType));
 content=`<div class="local-scenes">${[['walk','今天去哪遛狗','散步路线'],['life','附近的养宠生活','宠物友好地点'],['help','同城经验与求助','本地照护经验']].map(([id,l,t])=>`<button data-action="local-scene" data-id="${id}" class="${ui.localScene===id?'active':''}">${icon(id==='walk'?'discover':id==='life'?'pin':'chat')}<strong>${l}</strong><small>${id==='walk'?'慢慢走，闻闻新气味':id==='life'?'休息、饮水与周末小事':'聊聊照顾伙伴的经验'}</small>${icon('arrow')}</button>`).join('')}</div>${!ui.localScene?'':`<div class="scene-heading"><h2>${ui.localScene==='walk'?'今天去哪遛狗':ui.localScene==='life'?'附近的养宠生活':'同城经验与求助'}</h2><span class="fine">体验地点 · 出行前请核实</span></div><details class="filter-disclosure"><summary>${e(ui.localCity||'所有城市')} · 调整筛选</summary><form id="local-filter" class="filter-bar"><label>城市<select name="city"><option value="">所有城市</option>${['深圳','广州'].map(x=>`<option ${ui.localCity===x?'selected':''}>${x}</option>`).join('')}</select></label><label>区域<select name="district"><option value="">所有区域</option>${[...new Set(localContents.filter(r=>!ui.localCity||r.city===ui.localCity).map(r=>r.district))].map(x=>`<option ${ui.localDistrict===x?'selected':''}>${x}</option>`).join('')}</select></label><label>宠物<select name="species">${['全部','猫咪','狗狗','其他宠物'].map(x=>`<option ${ui.localSpecies===x?'selected':''}>${x}</option>`).join('')}</select></label><label>内容<select name="type"><option value="">所有类型</option>${[...new Set(localContents.map(p=>p.type))].map(x=>`<option ${ui.localType===x?'selected':''}>${x}</option>`).join('')}</select></label><button class="btn secondary">筛选</button>${b('重置','local-clear',{kind:'text'})}</form></details>${resources.length?`<div class="resource-grid">${resources.map(r=>`<article class="resource-card"><div class="resource-visual">${icon(r.type==='散步路线'?'discover':r.type==='本地照护经验'?'note':'pin')}<span>${e(r.type)}</span></div><div class="resource-body"><div class="tags">${tag('体验地点','warm')}${tag(r.city+' · '+r.district,'subtle')}</div><h3>${e(r.title)}</h3><p>${e(r.text)}</p><div class="resource-actions">${b('查看内容','resource-detail',{id:r.id,kind:'text',iconName:'arrow'})}${ib(s.resourceSaved.includes(r.id)?'取消收藏资源':'收藏资源','resource-save',r.id,'bookmark')}</div></div></article>`).join('')}</div>`:empty('暂时没有这类本地内容','可以切换区域或重置筛选。',b('重置筛选','local-clear',{kind:'secondary'}))}`} `;
 }
 return heading('DISCOVER','发现','')+`<div class="discovery-tabs" role="group" aria-label="发现栏目">${[['bottle','bottle','宠物漂流瓶'],['square','people','宠友广场'],['local','pin','同城探索']].map(([id,ic,l])=>`<button class="${ui.discoverTab===id?'active':''}" data-action="discover-tab" data-id="${id}" aria-pressed="${ui.discoverTab===id}">${icon(ic)}<span>${l}</span></button>`).join('')}</div>${content}`;
}
